
; #region 全局变量
  

GroupAdd "taskbar_window", "ahk_class Shell_TrayWnd" 
GroupAdd "taskbar_window", "ahk_class Shell_SecondaryTrayWnd"

GroupAdd "chinese_app", "ahk_exe chrome.exe"
GroupAdd "chinese_app", "ahk_class XLMAIN"
GroupAdd "chinese_app", "ahk_class OpusApp"
GroupAdd "chinese_app", "ahk_class WeChatMainWnorPC"

GroupAdd "english_app", "ahk_exe Code.exe"

GroupAdd "chinese_english", "ahk_group english_app"
GroupAdd "chinese_english", "ahk_group chinese_app"

GroupAdd "black_office", "Excel", , "-"
GroupAdd "black_office", "PowerPoint", , "-"
GroupAdd "black_office", "Word", , "-"
GroupAdd "black_office", "Visio Professional", , "-"

GroupAdd "group_office", "ahk_class XLMAIN"
GroupAdd "group_office", "ahk_class OpusApp"	 
GroupAdd "group_office", "ahk_class PPTFrameClass" 
GroupAdd "group_office", "ahk_class VISIOA"

GroupAdd "candidate_window", "ahk_class wetype.flutter.setting"
GroupAdd "candidate_window", "ahk_class SoPY_Comp"	
GroupAdd "candidate_window", "ahk_class BaseGui"		
GroupAdd "candidate_window", "ahk_class ApplicationFrameWindow"	

GroupAdd "system_group", "ahk_class WorkerW"
GroupAdd "system_group", "ahk_class Progman"
GroupAdd "system_group", "ahk_class Shell_TrayWnd"
GroupAdd "system_group", "ahk_class Shell_SecondaryTrayWnd"

GroupAdd "text_app", "ahk_exe Notepad.exe"

GroupAdd "ctrlw_group", "ahk_exe clash-verge.exe"
GroupAdd "ctrlw_group", "ahk_exe Evernote.exe"
GroupAdd "ctrlw_group", "ahk_exe mailmaster.exe"
GroupAdd "ctrlw_group", "ahk_exe IDMan.exe"
GroupAdd "ctrlw_group", "ahk_exe WindowSpyDpi.exe"
GroupAdd "ctrlw_group", "ahk_exe Ditto.exe"
GroupAdd "ctrlw_group", "ahk_exe Qianwen.exe"
GroupAdd "ctrlw_group", "ahk_exe Doubao.exe"
GroupAdd "ctrlw_group", "ahk_exe ApplicationFrameHost.exe"
GroupAdd "ctrlw_group", "ahk_exe 哔哩哔哩.exe"

GroupAdd "video_group", "ahk_exe 哔哩哔哩.exe"
; GroupAdd "video_group", "ahk_exe WindowSpyDpi.exe"
; GroupAdd "video_group", "ahk_exe Ditto.exe"


system_color_map := Map(
    "Black",    0x000000, ; 黑色
    "Silver",   0xC0C0C0, ; 银色
    "Gray",     0x808080, ; 灰色
    "White",    0xFFFFFF, ; 白色
    "Maroon",   0x000080, ; 栗色 (深红)
    "Red",      0x0000FF, ; 红色
    "Purple",   0x800080, ; 紫色
    "Fuchsia",  0xFF00FF, ; 品红 (洋红)
    "Green",    0x008000, ; 绿色 (深绿)
    "Lime",     0x00FF00, ; 青柠色 (亮绿)
    "Olive",    0x008080, ; 橄榄色
    "Yellow",   0x00FFFF, ; 黄色
    "Navy",     0x800000, ; 海军蓝 (深蓝)
    "Blue",     0xFF0000, ; 蓝色
    "Teal",     0x808000, ; 水鸭色 (蓝绿)
    "Aqua",     0xFFFF00  ; 水绿色 (青色)
)

color_map := Map(
    1, "22046e",
    2, "0x9b4901",
    3, "Yellow",
    4, "Green",
    5, "Aqua",
    6, "Navy",
    7, "Purple",
    8, "0c0c0c",
    9, "826d44",
    10, "7d8380"
)

selection_type_map := Map(
    0, "none",
    1, "slides",
    2, "shapes",
    3, "text"
)

SHAPE_TYPE_MAP := Map(
    ; 数值, 常量名称,                              ; 说明
    30, "mso3DModel",                            ; 3D 模型
    1, "msoAutoShape",                           ; 自选图形
    2, "msoCallout",                             ; 标注
    20, "msoCanvas",                             ; 画布
    3, "msoChart",                               ; 图表
    4, "msoComment",                             ; 评论
    27, "msoContentApp",                         ; 内容 Office 加载项
    21, "msoDiagram",                            ; 图示
    7, "msoEmbeddedOLEObject",                   ; 嵌入式 OLE 对象
    8, "msoFormControl",                         ; 窗体控件
    5, "msoFreeform",                            ; 任意多边形
    28, "msoGraphic",                            ; 图形
    6, "msoGroup",                               ; 组
    24, "msoIgxGraphic",                         ; SmartArt 图形
    22, "msoInk",                                ; 墨迹
    23, "msoInkComment",                         ; 墨迹批注
    9, "msoLine",                                ; 折线图
    31, "msoLinked3DModel",                      ; 链接的 3D 模型
    29, "msoLinkedGraphic",                      ; 链接的图形
    10, "msoLinkedOLEObject",                    ; 链接 OLE 对象
    11, "msoLinkedPicture",                      ; 链接图片
    16, "msoMedia",                              ; 媒体
    12, "msoOLEControlObject",                   ; OLE 控件对象
    13, "msoPicture",                            ; 图片
    14, "msoPlaceholder",                        ; 占位符
    18, "msoScriptAnchor",                       ; 脚本定位标记
    -2, "msoShapeTypeMixed",                     ; 混合形状类型
    25, "msoSlicer",                             ; 切片器
    19, "msoTable",                              ; 表格
    17, "msoTextBox",                            ; 文本框
    15, "msoTextEffect",                         ; 文本效果
    26, "msoWebVideo"                            ; Web 视频
)

TEXT_4 := [
    "智领未来", "数实融合", "新质生产力", "绿色低碳",
    "自主创新", "全球布局", "提质增效", "降本增效",
    "敏捷迭代", "深度赋能", "生态共赢", "价值重塑",
    "精准洞察", "全域营销", "沉浸体验", "无缝协同",
    "智慧决策", "韧性增长", "安全可控", "开源节流",
    "跨界融合", "场景创新", "数据驱动", "云端协同",
    "人机协作", "虚实共生", "零碳转型", "循环经济",
    "高端智造", "专精特新", "品牌焕新", "用户至上",
    "长期主义", "稳健经营", "风险对冲", "合规先行",
    "人才强企", "文化铸魂", "组织激活", "效能飞跃",
    "技术突破", "产业升级", "市场深耕", "渠道下沉",
    "内容种草", "私域运营", "直播赋能", "社交裂变",
    "AI 赋能", "算力爆发", "算法优化", "模型迭代",
    "量子前沿", "生物制造", "空天经济", "深海探测",
    "能源革命", "储能创新", "氢能应用", "光伏增效",
    "智能网联", "车路协同", "低空经济", "无人配送",
    "元宇宙境", "数字孪生", "区块链网", "隐私计算",
    "柔性生产", "定制服务", "即时响应", "极致体验",
    "开放合作", "共享经济", "平台生态", "链式反应",
    "破局重生", "弯道超车", "换道领跑", "降维打击",
    "精细运营", "精益管理", "标准引领", "质量强国",
    "乡村振兴", "共同富裕", "民生福祉", "社会和谐",
    "文化自信", "国潮崛起", "东方美学", "匠心传承",
    "健康中国", "智慧医疗", "康养结合", "生命科学",
    "教育公平", "终身学习", "技能提升", "产教融合",
    "法治社会", "诚信体系", "公平正义", "平安建设",
    "美丽中国", "生态文明", "人与自然", "和谐共生"
]

TEXT_8 := [
    "数字转型实施方案", "项目管理优化策略", "战略规划部署方案", "宏观趋势分析报告",
    "竞争格局应对策略", "产业升级指导纲要", "区域发展布局规划", "长期愿景实施路径",
    "短期目标行动指南", "资源配置优化方案", "运营效能提升方案", "供应链路协同优化",
    "库存管理精简策略", "物流配送提速计划", "生产流程再造工程", "精益管理推行方案",
    "风险防控体系建设", "合规审计整改报告", "市场分析研究报告", "品牌建设推广方案",
    "营销渠道拓展计划", "客户画像分析洞察", "竞品对标分析报告", "公关危机处理预案",
    "产品创新设计方案", "技术架构升级方案", "数据安全防护措施", "用户体验改进计划",
    "团队建设发展规划", "人才培养实施方案", "成本控制优化策略", "效率提升行动计划",
    "质量管控体系构建", "业务流程改进方案", "客户服务提升计划", "技术架构升级方案",
    "人才培养实施方案", "质量管控体系构建", "成本控制优化策略", "效率提升行动计划",
    "品牌建设推广方案", "数据安全防护措施", "用户体验改进计划", "战略规划部署方案",
    "宏观趋势分析报告", "竞争格局应对策略", "产业升级指导纲要", "区域发展布局规划",
    "长期愿景实施路径", "短期目标行动指南", "资源配置优化方案", "顶层设计构建方案",
    "年度经营计划大纲", "运营效能提升方案", "供应链条协同优化", "库存管理精简策略",
    "物流配送提速计划", "生产流程再造工程", "精益管理推行方案", "风险防控体系建设"
]

TEXT_20 := [
    "深化数字化转型战略，全面推动企业高质量发展进程",
    "优化供应链管理流程，显著提升整体运营效率与效益",
    "加强核心技术自主研发，构建可持续创新竞争壁垒",
    "拓展全球市场业务布局，实现多元化国际发展战略",
    "完善人才培养激励机制，打造高素质专业化精英团队",
    "推进绿色低碳生产模式，践行社会责任与可持续发展",
    "强化风险防控体系建设，确保企业经营安全稳健运行",
    "提升客户服务体验标准，树立行业领先品牌形象口碑",
    "加速智能工厂建设步伐，引领制造业转型升级新方向",
    "整合线上线下营销渠道，最大化提升市场份额占有率",
    "落实精细化管理措施，有效控制成本并提高利润率",
    "探索新兴商业模式应用，激发组织内部活力与创新力",
    "构建开放共赢生态平台，携手合作伙伴共创美好未来",
    "加大研发投入力度，突破关键领域技术瓶颈与制约",
    "优化资产配置结构，实现资本运作效率最大化目标",
    "建立数据驱动决策机制，精准洞察市场趋势与变化",
    "弘扬企业文化核心价值观，凝聚全员奋斗共识与力量",
    "实施品牌国际化战略，提升中国智造全球影响力",
    "完善售后服务网络体系，快速响应客户需求与反馈",
    "推动产业协同创新发展，构建现代化经济体系新格局"
]

TEXT_30 := [
    "深化数字化转型战略全面布局，以创新驱动引领企业高质量可持续发展新征程",
    "优化全链路供应链管理流程，显著提升整体运营效率并最大化经济效益产出",
    "加强核心技术自主研发创新力度，构建具有全球竞争力的可持续技术壁垒",
    "拓展全球化市场业务战略布局，实现多元化国际发展战略与市场份额双增长",
    "完善全方位人才培养激励机制，打造高素质专业化精英团队以赋能组织发展",
    "深入推进绿色低碳生产模式转型，积极践行社会责任并实现可持续生态发展",
    "强化多层次风险防控体系建设，确保企业在复杂环境中经营安全稳健运行",
    "全面提升客户服务体验标准体系，树立行业领先品牌形象与卓越口碑影响力",
    "加速智能化数字工厂建设步伐，引领传统制造业转型升级与高质量发展方向",
    "深度整合线上线下全渠道营销，最大化提升市场份额占有率与品牌渗透能力",
    "全面落实精细化运营管理措施，有效控制成本支出并显著提高净利润率水平",
    "积极探索新兴商业模式创新应用，充分激发组织内部活力与持续创新驱动力",
    "构建开放共赢的产业生态平台，携手合作伙伴共创美好未来与商业价值新高",
    "加大前沿技术研发投入支持力度，突破关键领域技术瓶颈制约并掌握主动权",
    "优化多元化资产配置结构组合，实现资本运作效率最大化与企业价值目标",
    "建立数据驱动型科学决策机制，精准洞察市场趋势变化并快速响应客户需求",
    "弘扬企业文化核心价值观理念，凝聚全员奋斗共识与力量以推动战略目标达成",
    "全面实施品牌国际化发展战略，显著提升中国智造在全球市场的影响力地位",
    "完善覆盖全国售后服务网络体系，快速响应客户需求反馈并提升满意度指标",
    "推动产业链协同创新发展模式，构建现代化经济体系新格局并增强抗风险能力"
]



TARGET_ITEMS := Map(
    ; --- run app ----------------------------------------------------------------
    "app_wechat", Map("info", "微信", "type", "run"),
    "app_qqlive", Map("info", "腾讯视频", "type", "run"),
    "app_wxwork", Map("info", "企业微信", "type", "run"),
    "app_wemeet", Map("info", "腾讯会议", "type", "run"),
    "app_qianwen", Map("info", "通义千问", "type", "run"),
    "url_deepseek", Map("info", "DeepSeek", "type", "run"),
    "url_coze", Map("info", "扣 子", "type", "run"),
    "url_kimi", Map("info", "Kimi", "type", "run"),
    "app_doubao", Map("info", "豆 包", "type", "run"),
    "CMD_DESKTOP_NOTES_1", Map("info", "VS Code 快捷键", "type", "run"),
    "CMD_DESKTOP_NOTES_2", Map("info", "CMD_DESKTOP_NOTE_2", "type", "run"),
    "CMD_DESKTOP_NOTES_3", Map("info", "CMD_DESKTOP_NOTE_3", "type", "run"),
    "url_lovart", Map("info", "Lovart", "type", "run"),
    "url_claude", Map("info", "Claude", "type", "run"),
    "url_chatgpt", Map("info", "ChatGPT", "type", "run"),
    "url_gemini", Map("info", "Gemini", "type", "run"),
    "url_perplexity", Map("info", "perplexity", "type", "run"),
    "url_copilot", Map("info", "Copilot", "type", "run"),
    "app_everything", Map("info", "Everything", "type", "run"),
    "app_eagle", Map("info", "Eagle", "type", "run"),
    "app_evernote", Map("info", "印象笔记", "type", "run"),
    "url_zhyw", Map("info", "智慧运维平台", "type", "run"),
    "file_whdj_server", Map("info", "维护登记", "type", "run"),
    "url_zhlmt", Map("info", "分发平台", "type", "run"),
    "url_wjx", Map("info", "问卷星", "type", "run"),
    "app_vscode", Map("info", "Visual Studio Code", "type", "run"),
    "app_spy", Map("info", "Window Spy", "type", "run"),
    "FILE_SHORTCUT_TABLE", Map("info", "Shortcut Table", "type", "run"),
    "url_ahk_help", Map("info", "AutoHotkey Help", "type", "run"),
    "url_ahk_forum", Map("info", "www.autohotkey.com", "type", "run"),
    "app_notepad", Map("info", "记事本", "type", "run"),
    "app_excel", Map("info", "Excel", "type", "run"),
    "app_baidunetdisk", Map("info", "百度网盘", "type", "run"),
    "url_jd", Map("info", "京 东", "type", "run"),
    "url_xianyu", Map("info", "闲 鱼", "type", "run"),
    "url_taobao", Map("info", "淘 宝", "type", "run"),
    "app_word", Map("info", "Word", "type", "run"),
    "app_mailmaster", Map("info", "网易邮箱大师", "type", "run"),
    "app_youdaodict", Map("info", "有道词典", "type", "run"),
    "APP_BILIBILI", Map("info", "哔哩哔哩", "type", "run"),
    "URL_BILIBILI", Map("info", "哔哩哔哩", "type", "run"),
    "url_qqlive", Map("info", "腾讯视频", "type", "run"),
    "url_xiaohongshu", Map("info", "小红书", "type", "run"),
    "url_iqiyi", Map("info", "爱奇艺", "type", "run"),
    "url_douyin", Map("info", "抖 音", "type", "run"),
    "url_yunwu", Map("info", "云雾API", "type", "run"),
    "pbb_path_server", Map("info", "服务器上的排班表文件夹", "type", "run"),
    "wh_path_server", Map("info", "服务器上的维护文件夹", "type", "run"),
    "gr_path_server", Map("info", "服务器上的个人文件夹", "type", "run"),

    ; --- func ----------------------------------------------------------------
    "min_window_under_mouse", Map("info", "最小化窗口", "type", "func"),
    "func_wins", Map("info", "Win+S", "type", "func"),
    "func_ctrls", Map("info", "保 存", "type", "func"),
    "save_as", Map("info", "另存为……", "type", "func"),
    "copy_format", Map("info", "复 制", "type", "func"),
    "func_ctrlshiftw", Map("info", "Ctrl+Shift+W", "type", "func"),
    "smart_ctrlw", Map("info", "Ctrl+W", "type", "func"),
    "func_winw", Map("info", "Win+W", "type", "func"),
    "shutdown_computer", Map("info", "关 机", "type", "func"),
    "restart_computer", Map("info", "重 启", "type", "func"),
    "lock_screen", Map("info", "锁 定 屏 幕", "type", "func"),
    "close_window_under_mouse", Map("info", "关闭窗口", "type", "func"),
    "max_window", Map("info", "最大化窗口", "type", "func"),
    "left_window", Map("info", "窗口靠左半边", "type", "func"),
    "right_window", Map("info", "窗口靠右半边", "type", "func"),
    "paste_format", Map("info", "粘贴格式", "type", "func"),
    "func_wind", Map("info", "显示桌面", "type", "func"),
    "close_ppt_process", Map("info", "关闭PPT进程", "type", "func"),
    "open_current_path", Map("info", "文件夹", "type", "func"),
    "open_recycle_bin", Map("info", "回收站", "type", "func"),
    "do_nothing", Map("info", "Cancel ?", "type", "func"),
    "reload_me", Map("info", "Reload QWERT ?", "type", "func"),
    "suspend_me", Map("info", "Suspend QWERT ?", "type", "func"),
    "ExitApp", Map("info", "Shutdown QWERT ?", "type", "func"),
    "func_cancel", Map("info", "Cancel ?", "type", "func"),
    "func_ctrlx", Map("info", "剪 切", "type", "func"),
    "add_slide_from_eagle", Map("info", "从eagle中复制PPT页面", "type", "func"),

    ; --- mso ----------------------------------------------------------------
    "ObjectsAlignLeftSmart", Map("info", "左对齐", "type", "mso"),
    "ObjectsAlignCenterHorizontalSmart", Map("info", "水平居中", "type", "mso"),
    "ObjectsAlignRightSmart", Map("info", "右对齐", "type", "mso"),
    "ObjectsAlignTopSmart", Map("info", "顶部对齐", "type", "mso"),
    "ObjectsAlignMiddleVerticalSmart", Map("info", "垂直居中", "type", "mso"),
    "ObjectsAlignBottomSmart", Map("info", "底部对齐", "type", "mso"),
    "AlignObjects", Map("info", "对齐对象菜单", "type", "mso"),
    "ObjectsDistributeLeft", Map("info", "横向分布", "type", "mso"),
    "ObjectsDistributeCenter", Map("info", "横向居中分布", "type", "mso"),
    "ObjectsDistributeRight", Map("info", "横向右分布", "type", "mso"),
    "ObjectsDistributeTop", Map("info", "纵向分布", "type", "mso"),
    "ObjectsDistributeMiddle", Map("info", "纵向居中分布", "type", "mso"),
    "ObjectsDistributeBottom", Map("info", "纵向下分布", "type", "mso"),
    "ObjectSendToBack", Map("info", "置于底层", "type", "mso"),
    "ObjectBringToFront", Map("info", "置于顶层", "type", "mso"),
    "ObjectSendBackward", Map("info", "下移一层", "type", "mso"),
    "ObjectBringForward", Map("info", "上移一层", "type", "mso"),
    "SelectionPane", Map("info", "选择窗格", "type", "mso"),
    "GroupShapes", Map("info", "组合", "type", "mso"),
    "UngroupShapes", Map("info", "取消组合", "type", "mso"),
    "RegroupShapes", Map("info", "重新组合", "type", "mso"),
    "RotateRight", Map("info", "向右旋转90度", "type", "mso"),
    "RotateLeft", Map("info", "向左旋转90度", "type", "mso"),
    "RotateFlipHorizontal", Map("info", "水平翻转", "type", "mso"),
    "RotateFlipVertical", Map("info", "垂直翻转", "type", "mso"),
    "RotateFlipHorizontalFlipVertical", Map("info", "水平垂直翻转", "type", "mso"),
    "RotateFlipHorizontalRotate90Right", Map("info", "右旋+水平翻转", "type", "mso"),
    "RotateFlipVerticalRotate90Right", Map("info", "右旋+垂直翻转", "type", "mso"),
    "EditShape", Map("info", "编辑顶点", "type", "mso"),
    "ChangeShape", Map("info", "更改形状", "type", "mso"),
    "InkToShape", Map("info", "墨迹转换为形状", "type", "mso"),
    "ConvertToFreeform", Map("info", "转换为自由曲线", "type", "mso"),
    "AlignTextLeft", Map("info", "文本左对齐", "type", "mso"),
    "AlignTextCenter", Map("info", "文本居中", "type", "mso"),
    "AlignTextRight", Map("info", "文本右对齐", "type", "mso"),
    "AlignTextJustify", Map("info", "文本两端对齐", "type", "mso"),
    "AlignTextDistribute", Map("info", "文本分散对齐", "type", "mso"),
    "JustifyLow", Map("info", "文本低对齐", "type", "mso"),
    "AlignTextTop", Map("info", "文本顶端对齐", "type", "mso"),
    "AlignTextMiddle", Map("info", "文本中部对齐", "type", "mso"),
    "AlignTextBottom", Map("info", "文本底端对齐", "type", "mso"),
    "TextDirectionRotate270Normal", Map("info", "文字方向：竖排", "type", "mso"),
    "TextDirectionRotate90Normal", Map("info", "文字方向：竖排(反向)", "type", "mso"),
    "TextDirectionHorizontal", Map("info", "文字方向：横排", "type", "mso"),
    "Bullets", Map("info", "项目符号", "type", "mso"),
    "Numbering", Map("info", "编号", "type", "mso"),
    "LineSpacing", Map("info", "行距", "type", "mso"),
    "IncreaseIndent", Map("info", "增加缩进", "type", "mso"),
    "DecreaseIndent", Map("info", "减少缩进", "type", "mso"),
    "HangingIndent", Map("info", "悬挂缩进", "type", "mso"),
    "Font", Map("info", "字体设置", "type", "mso"),
    "FontSize", Map("info", "字号", "type", "mso"),
    "FontSizeGrow", Map("info", "增大字号", "type", "mso"),
    "FontSizeShrink", Map("info", "减小字号", "type", "mso"),
    "Bold", Map("info", "加粗", "type", "mso"),
    "Italic", Map("info", "倾斜", "type", "mso"),
    "Underline", Map("info", "下划线", "type", "mso"),
    "Shadow", Map("info", "阴影", "type", "mso"),
    "Strikethrough", Map("info", "删除线", "type", "mso"),
    "ChangeCase", Map("info", "更改大小写", "type", "mso"),
    "Subscript", Map("info", "下标", "type", "mso"),
    "Superscript", Map("info", "上标", "type", "mso"),
    "ClearFormatting", Map("info", "清除格式", "type", "mso"),
    "Highlight", Map("info", "文本高亮", "type", "mso"),
    "FontColor", Map("info", "字体颜色", "type", "mso"),
    "ShapeFillColorPicker", Map("info", "形状填充", "type", "mso"),
    "ShapeOutlineColorPicker", Map("info", "形状轮廓", "type", "mso"),
    "ShapeEffects", Map("info", "形状效果", "type", "mso"),
    "QuickStylesGallery", Map("info", "快速样式", "type", "mso"),
    "LineStyle", Map("info", "线条样式", "type", "mso"),
    "LineWeight", Map("info", "线条粗细", "type", "mso"),
    "LineDashes", Map("info", "虚线线型", "type", "mso"),
    "LineArrowheads", Map("info", "箭头样式", "type", "mso"),
    "PictureChange", Map("info", "更改图片", "type", "mso"),
    "PictureReset", Map("info", "重设图片", "type", "mso"),
    "Crop", Map("info", "裁剪", "type", "mso"),
    "CropToShape", Map("info", "裁剪为形状", "type", "mso"),
    "AspectRatio", Map("info", "纵横比", "type", "mso"),
    "CompressPictures", Map("info", "压缩图片", "type", "mso"),
    "PictureColor", Map("info", "图片颜色", "type", "mso"),
    "PictureArtisticEffects", Map("info", "艺术效果", "type", "mso"),
    "PictureCorrections", Map("info", "图片更正", "type", "mso"),
    "PictureBorder", Map("info", "图片边框", "type", "mso"),
    "RemoveBackground", Map("info", "删除背景", "type", "mso"),
    "OnlinePicture", Map("info", "联机图片", "type", "mso"),
    "InsertScreenshot", Map("info", "屏幕截图", "type", "mso"),
    "PictureCropAspectRatio1To1", Map("info", "图片裁剪宽高比1:1", "type", "mso"),
    "PictureCropAspectRatio2To3", Map("info", "图片裁剪宽高比2:3", "type", "mso"),
    "PictureCropAspectRatio3To4", Map("info", "图片裁剪宽高比3:4", "type", "mso"),
    "PictureCropAspectRatio3To5", Map("info", "图片裁剪宽高比3:5", "type", "mso"),
    "PictureCropAspectRatio4To5", Map("info", "图片裁剪宽高比4:5", "type", "mso"),
    "PictureCropAspectRatio3To2", Map("info", "图片裁剪宽高比3:2", "type", "mso"),
    "PictureCropAspectRatio4To3", Map("info", "图片裁剪宽高比4:3", "type", "mso"),
    "PictureCropAspectRatio5To3", Map("info", "图片裁剪宽高比5:3", "type", "mso"),
    "PictureCropAspectRatio5To4", Map("info", "图片裁剪宽高比5:4", "type", "mso"),
    "PictureCropAspectRatio16To9", Map("info", "图片裁剪宽高比16:9", "type", "mso"),
    "PictureCropAspectRatio16To10", Map("info", "图片裁剪宽高比16:10", "type", "mso"),
    "PictureFillCrop", Map("info", "图片填充裁剪", "type", "mso"),
    "PictureFitCrop", Map("info", "图片适应裁剪", "type", "mso"),
    "NudgeUp", Map("info", "向上微调", "type", "mso"),
    "NudgeDown", Map("info", "向下微调", "type", "mso"),
    "NudgeLeft", Map("info", "向左微调", "type", "mso"),
    "NudgeRight", Map("info", "向右微调", "type", "mso"),
    "SizeUp", Map("info", "向上增大", "type", "mso"),
    "SizeDown", Map("info", "向下减小", "type", "mso"),
    "SizeLeft", Map("info", "向左增大", "type", "mso"),
    "SizeRight", Map("info", "向右减小", "type", "mso"),
    "SizeObjectDialog", Map("info", "大小和位置", "type", "mso"),
    "SnapToGrid", Map("info", "对齐网格", "type", "mso"),
    "SnapToShapes", Map("info", "对齐对象", "type", "mso"),
    "Gridlines", Map("info", "网格线", "type", "mso"),
    "Guides", Map("info", "参考线", "type", "mso"),
    "ViewZoom", Map("info", "缩放", "type", "mso"),
    "FitToWindow", Map("info", "适应窗口大小", "type", "mso"),
    "ZoomToSelection", Map("info", "缩放至所选内容", "type", "mso"),
    "InsertRowsAbove", Map("info", "在上方插入行", "type", "mso"),
    "InsertRowsBelow", Map("info", "在下方插入行", "type", "mso"),
    "InsertColumnsLeft", Map("info", "在左侧插入列", "type", "mso"),
    "InsertColumnsRight", Map("info", "在右侧插入列", "type", "mso"),
    "DeleteRows", Map("info", "删除行", "type", "mso"),
    "DeleteColumns", Map("info", "删除列", "type", "mso"),
    "MergeCells", Map("info", "合并单元格", "type", "mso"),
    "SplitCells", Map("info", "拆分单元格", "type", "mso"),
    "DistributeRows", Map("info", "平均分布各行", "type", "mso"),
    "DistributeColumns", Map("info", "平均分布各列", "type", "mso"),
    "TableBorders", Map("info", "边框", "type", "mso"),
    "TableFillColor", Map("info", "底纹", "type", "mso"),
    "ChartType", Map("info", "更改图表类型", "type", "mso"),
    "ChartData", Map("info", "编辑数据", "type", "mso"),
    "ChartLayout", Map("info", "图表布局", "type", "mso"),
    "ChartStyles", Map("info", "图表样式", "type", "mso"),
    "ChartAxes", Map("info", "坐标轴", "type", "mso"),
    "ChartGridlines", Map("info", "网格线", "type", "mso"),
    "ChartLegend", Map("info", "图例", "type", "mso"),
    "ChartDataLabels", Map("info", "数据标签", "type", "mso"),
    "ChartTrendline", Map("info", "趋势线", "type", "mso"),
    "SmartArtAddShapeAfter", Map("info", "添加形状(后)", "type", "mso"),
    "SmartArtAddShapeBefore", Map("info", "添加形状(前)", "type", "mso"),
    "SmartArtAddShapeAbove", Map("info", "添加形状(上)", "type", "mso"),
    "SmartArtAddShapeBelow", Map("info", "添加形状(下)", "type", "mso"),
    "SmartArtChangeHierarchy", Map("info", "更改层次结构", "type", "mso"),
    "SmartArtRTL", Map("info", "从右向左", "type", "mso"),
    "SmartArtLarger", Map("info", "增大", "type", "mso"),
    "SmartArtSmaller", Map("info", "减小", "type", "mso"),
    "SmartArtReset", Map("info", "重设", "type", "mso"),
    "HyperlinkInsert", Map("info", "插入超链接", "type", "mso"),
    "Duplicate", Map("info", "复制选中对象", "type", "mso"),
    "Delete", Map("info", "删除", "type", "mso"),
    "Copy", Map("info", "复制", "type", "mso"),
    "Paste", Map("info", "粘贴", "type", "mso"),
    "PasteSourceFormatting", Map("info", "保留源格式粘贴", "type", "mso"),
    "PasteMergeFormatting", Map("info", "合并格式粘贴", "type", "mso"),
    "PastePicture", Map("info", "粘贴为图片", "type", "mso"),
    "Save", Map("info", "保存", "type", "mso"),
    "Undo", Map("info", "撤销", "type", "mso"),
    "Redo", Map("info", "恢复", "type", "mso"),
    "SelectAll", Map("info", "全选", "type", "mso"),
    "Find", Map("info", "查找", "type", "mso"),
    "Replace", Map("info", "替换", "type", "mso"),
    "AutoSaveSwitch", Map("info", "自动保存到OneDriver", "type", "mso"),
    "FileNewDefault", Map("info", "新建默认文件", "type", "mso"),
    "FileOpenUsingBackstage", Map("info", "利用后台视图打开文件", "type", "mso"),
    "FileSave", Map("info", "保存文件", "type", "mso"),
    "FileSendAsAttachment", Map("info", "当作附件发送", "type", "mso"),
    "FilePrintQuick", Map("info", "快速打印", "type", "mso"),
    "PrintPreviewAndPrint", Map("info", "打印预览", "type", "mso"),
    "Spelling", Map("info", "拼写检查", "type", "mso"),
    "RedoOrRepeat", Map("info", "重做", "type", "mso"),
    "SlideShowFromBeginning", Map("info", "从头开始播放幻灯片放映", "type", "mso"),
    "PasteSpecialDialog", Map("info", "粘贴特殊对话框", "type", "mso"),
    "Cut", Map("info", "剪切", "type", "mso"),
    "PasteDuplicate", Map("info", "复制并粘贴", "type", "mso"),
    "FormatPainter", Map("info", "格式刷", "type", "mso"),
    "ShowClipboard", Map("info", "显示剪贴板", "type", "mso"),
    "DuplicateSelectedSlides", Map("info", "复制所选幻灯片", "type", "mso"),
    "SlidesFromOutline", Map("info", "从大纲生成幻灯片", "type", "mso"),
    "SlidesReuseSlides", Map("info", "重用幻灯片", "type", "mso"),
    "SlideReset", Map("info", "重置幻灯片", "type", "mso"),
    "SectionAdd", Map("info", "添加分区", "type", "mso"),
    "SectionRename", Map("info", "重命名分区", "type", "mso"),
    "SectionMergeWithPrevious", Map("info", "合并到前一个分区", "type", "mso"),
    "SectionRemoveAll", Map("info", "移除所有分区", "type", "mso"),
    "SectionCollapseAll", Map("info", "折叠所有分区", "type", "mso"),
    "SectionExpandAll", Map("info", "展开所有分区", "type", "mso"),
    "FontSizeIncrease", Map("info", "字体大小增加", "type", "mso"),
    "FontSizeDecrease", Map("info", "字体大小减少", "type", "mso"),
    "ClearFormatting", Map("info", "清除格式", "type", "mso"),
    "Bold", Map("info", "加粗", "type", "mso"),
    "Italic", Map("info", "斜体", "type", "mso"),
    "Underline", Map("info", "下划线", "type", "mso"),
    "Shadow", Map("info", "阴影", "type", "mso"),
    "Strikethrough", Map("info", "删除线", "type", "mso"),
    "FontColorMoreColorsDialogPowerPoint", Map("info", "字体颜色对话框", "type", "mso"),
    "EyedropperFillText", Map("info", "填充文本取色器", "type", "mso"),
    "FontDialogPowerPoint", Map("info", "字体对话框", "type", "mso"),
    "BulletsAndNumberingBulletsDialog", Map("info", "着重号对话框", "type", "mso"),
    "BulletsAndNumberingNumberingDialog", Map("info", "编号对话框", "type", "mso"),
    "IndentDecrease", Map("info", "缩进减少", "type", "mso"),
    "IndentIncrease", Map("info", "缩进增加", "type", "mso"),
    "AlignLeft", Map("info", "居左对齐", "type", "mso"),
    "AlignCenter", Map("info", "居中对齐", "type", "mso"),
    "AlignRight", Map("info", "居右对齐", "type", "mso"),
    "AlignJustify", Map("info", "两端对齐", "type", "mso"),
    "AlignJustifyWithMixedLanguages", Map("info", "带多种语言的两端对齐", "type", "mso"),
    "AlignJustifyLow", Map("info", "低层次两端对齐", "type", "mso"),
    "ParagraphDistributed", Map("info", "分散对齐", "type", "mso"),
    "AlignJustifyThai", Map("info", "带泰语的两端对齐", "type", "mso"),
    "TextDirectionLeftToRight", Map("info", "文字方向-从左到右", "type", "mso"),
    "TextDirectionRightToLeft", Map("info", "文字方向-从右到左", "type", "mso"),
    "ParagraphMoreColumnsDialog", Map("info", "段落-更多栏", "type", "mso"),
    "TextDirectionMoreOptionsDialog", Map("info", "文本方向更多选项-对话框", "type", "mso"),
    "TextAlignMoreOptionsDialog", Map("info", "对齐-更多选项", "type", "mso"),
    "ConvertToSmartArtMoreSmartArtGraphicsDialog", Map("info", "转换为智能图形-更多智能图形", "type", "mso"),
    "PowerPointParagraphDialog", Map("info", "幻灯片段落-对话框", "type", "mso"),
    "ObjectBringToFront", Map("info", "对象-置于顶层", "type", "mso"),
    "ObjectSendToBack", Map("info", "对象-置于底层", "type", "mso"),
    "ObjectBringForward", Map("info", "对象-上移一层", "type", "mso"),
    "ObjectSendBackward", Map("info", "对象-下移一层", "type", "mso"),
    "ObjectsGroup", Map("info", "对象-组合", "type", "mso"),
    "ObjectsUngroup", Map("info", "对象-取消组合", "type", "mso"),
    "ObjectsRegroup", Map("info", "对象-重新组合", "type", "mso"),
    "ObjectsAlignLeftSmart", Map("info", "对象-智能对齐-居左", "type", "mso"),
    "ObjectsAlignCenterHorizontalSmart", Map("info", "对象-智能对齐-居中水平", "type", "mso"),
    "ObjectsAlignRightSmart", Map("info", "对象-智能对齐-居右", "type", "mso"),
    "ObjectsAlignTopSmart", Map("info", "对象-智能对齐-居上", "type", "mso"),
    "ObjectsAlignMiddleVerticalSmart", Map("info", "对象-智能对齐-居中垂直", "type", "mso"),
    "ObjectsAlignBottomSmart", Map("info", "对象-智能对齐-居下", "type", "mso"),
    "AlignDistributeHorizontally", Map("info", "对齐-水平分布", "type", "mso"),
    "AlignDistributeVertically", Map("info", "对齐-垂直分布", "type", "mso"),
    "ObjectsAlignRelativeToContainerSmart", Map("info", "对象-相对于容器对齐", "type", "mso"),
    "ObjectsAlignSelectedSmart", Map("info", "对象-对齐所选项", "type", "mso"),
    "ObjectRotationOptionsDialog", Map("info", "对象-旋转选项-对话框", "type", "mso"),
    "ObjectFillMoreColorsDialog", Map("info", "对象-填充-更多颜色", "type", "mso"),
    "EyedropperFill", Map("info", "取色器-填充", "type", "mso"),
    "ObjectPictureFill", Map("info", "对象-图片填充", "type", "mso"),
    "ShapeFillMoreGradientsDialog", Map("info", "形状-填充-更多渐变", "type", "mso"),
    "MoreTextureOptions", Map("info", "更多纹理选项", "type", "mso"),
    "ObjectBorderOutlineColorMoreColorsDialog", Map("info", "对象-边框/外框颜色-更多颜色", "type", "mso"),
    "EyedropperOutline", Map("info", "取色器-外框", "type", "mso"),
    "LineStylesDialog", Map("info", "线条样式-对话框", "type", "mso"),
    "ArrowsMore", Map("info", "更多箭头", "type", "mso"),
    "_3DBevelOptionsDialog", Map("info", "3D斜角选项-对话框", "type", "mso"),
    "ShadowOptionsDialog", Map("info", "阴影选项对话框", "type", "mso"),
    "ReflectionsMoreOptions", Map("info", "反射选项对话框", "type", "mso"),
    "GlowColorMoreColorsDialog", Map("info", "光晕颜色对话框", "type", "mso"),
    "EyedropperGlow", Map("info", "取色器-光晕", "type", "mso"),
    "GlowsMoreOptions", Map("info", "光晕-更多选项", "type", "mso"),
    "SoftEdgesMoreOptions", Map("info", "柔化边缘-更多选项", "type", "mso"),
    "_3DRotationOptionsDialog", Map("info", "3D旋转选项-对话框", "type", "mso"),
    "ObjectFormatDialog", Map("info", "对象格式对话框", "type", "mso"),
    "FindDialog", Map("info", "查找对话框", "type", "mso"),
    "ReplaceDialog", Map("info", "替换对话框", "type", "mso"),
    "FontsReplaceFonts", Map("info", "替换字对话框", "type", "mso"),
    "Dictate", Map("info", "听写", "type", "mso"),
    "TableInsert", Map("info", "插入表格", "type", "mso"),
    "TableDrawTable", Map("info", "绘制表格", "type", "mso"),
    "ExcelSpreadsheetInsert", Map("info", "插入Excel电子表格", "type", "mso"),
    "PictureInsertFromFilePowerPoint", Map("info", "从文件插入图片", "type", "mso"),
    "ClipArtInsertDialog", Map("info", "插入剪贴画对话框", "type", "mso"),
    "ScreenClipping", Map("info", "屏幕剪辑", "type", "mso"),
    "PhotoAlbumInsert", Map("info", "插入相册", "type", "mso"),
    "PhotoAlbumEdit", Map("info", "编辑相册", "type", "mso"),
    "IconInsertFromFile", Map("info", "从文件插入图标", "type", "mso"),
    "Insert3DModelFallback", Map("info", "插入3D模型备用", "type", "mso"),
    "Insert3DModelDefault", Map("info", "插入默认3D模型", "type", "mso"),
    "Insert3DModelFromFile", Map("info", "从文件插入3D模型", "type", "mso"),
    "Insert3DModelFromOnline", Map("info", "从在线插入3D模型", "type", "mso"),
    "SmartArtInsert", Map("info", "插入智能图形", "type", "mso"),
    "ChartInsert", Map("info", "插入图表", "type", "mso"),
    "OfficeExtensionsAppStore", Map("info", "应用商店", "type", "mso"),
    "OfficeExtensionsDialog", Map("info", "扩展对话框", "type", "mso"),
    "OfficeExtensionsManageOtherAddins", Map("info", "管理加载项", "type", "mso"),
    "MSPPTInsertTableofContents", Map("info", "插入摘要缩放定位", "type", "mso"),
    "SectionZoomInsert", Map("info", "插入节缩放定位", "type", "mso"),
    "SlideZoomInsert", Map("info", "插入幻灯片缩放定位", "type", "mso"),
    "ActionInsert", Map("info", "插入动作", "type", "mso"),
    "InsertNewComment", Map("info", "插入新批注", "type", "mso"),
    "TextBoxInsert", Map("info", "插入文本框", "type", "mso"),
    "TextBoxInsertHorizontal", Map("info", "插入横向文本框", "type", "mso"),
    "TextBoxInsertVertical", Map("info", "插入纵向文本框", "type", "mso"),
    "HeaderFooterInsert", Map("info", "插入页眉页脚", "type", "mso"),
    "DateAndTimeInsert", Map("info", "插入日期和时间", "type", "mso"),
    "NumberInsert", Map("info", "插入数字", "type", "mso"),
    "OleObjectctInsert", Map("info", "插入OLE对象", "type", "mso"),
    "EquationInsertNew", Map("info", "插入数学公式", "type", "mso"),
    "InkEquation", Map("info", "手写公式", "type", "mso"),
    "SymbolInsert", Map("info", "插入符号", "type", "mso"),
    "MovieFromClipOrganizerInsert", Map("info", "从剪贴画库插入影片", "type", "mso"),
    "MovieFromFileInsert", Map("info", "从文件插入影片", "type", "mso"),
    "SoundInsertFromFile", Map("info", "从文件插入声音", "type", "mso"),
    "SoundRecord", Map("info", "录制声音", "type", "mso"),
    "ObjectScreenRecording", Map("info", "屏幕录制", "type", "mso"),
    "InsertMSForms", Map("info", "插入MS表单", "type", "mso"),
    "FingerPaintingMode", Map("info", "通过触摸绘制", "type", "mso"),
    "InkEraser", Map("info", "笔划橡皮擦", "type", "mso"),
    "PointEraser", Map("info", "点状橡皮擦", "type", "mso"),
    "SegmentEraser", Map("info", "线段橡皮擦", "type", "mso"),
    "ShowRulerStencil", Map("info", "显示标尺", "type", "mso"),
    "InkToTextAnalysis", Map("info", "将墨迹转换为文本", "type", "mso"),
    "InkToShapeAnalysis", Map("info", "将墨迹转换为形状", "type", "mso"),
    "InkToMathAnalysis", Map("info", "将墨迹转换为数学公式", "type", "mso"),
    "MathInputEditor", Map("info", "墨迹公式编辑器", "type", "mso"),
    "Replay", Map("info", "墨迹重播", "type", "mso"),
    "ThemeSearchOfficeOnlinePowerPoint", Map("info", "启动在线主题搜索", "type", "mso"),
    "ThemeBrowseForThemesPowerPoint", Map("info", "浏览并选择主题", "type", "mso"),
    "ThemeSaveCurrentPowerPoint", Map("info", "保存当前主题", "type", "mso"),
    "ThemeColorsCreateNew", Map("info", "创建新的主题颜色", "type", "mso"),
    "ThemeColorsReset", Map("info", "重置主题颜色", "type", "mso"),
    "ThemeFontsCreateNew", Map("info", "创建新的主题字体", "type", "mso"),
    "SlideBackgroundFormatDialog", Map("info", "幻灯片背景格式对话框", "type", "mso"),
    "SlideBackgroundReset", Map("info", "重置幻灯片背景", "type", "mso"),
    "CustomSlideSize", Map("info", "自定义幻灯片大小", "type", "mso"),
    "LaunchFormatBackground", Map("info", "启动格式背景对话框", "type", "mso"),
    "DesignerPane", Map("info", "设计窗格", "type", "mso"),
    "TransitionPreview", Map("info", "过渡效果预览", "type", "mso"),
    "TransitionSoundLoopUntilNextSound", Map("info", "过渡声音循环直到下一个声音", "type", "mso"),
    "TransitionDuration", Map("info", "过渡持续时间", "type", "mso"),
    "SlideTransitionApplyToAll", Map("info", "将过渡应用于所有幻灯片", "type", "mso"),
    "SlideTransitionOnMouseClick", Map("info", "单击鼠标时换片", "type", "mso"),
    "SlideTransitionAutomaticallyAfter", Map("info", "自动换片", "type", "mso"),
    "AnimationPreview", Map("info", "动画预览", "type", "mso"),
    "AnimationAutoPreview", Map("info", "自动动画预览", "type", "mso"),
    "AnimationCustomEntranceDialog", Map("info", "自定义入场动画对话框", "type", "mso"),
    "AnimationCustomEmphasisDialog", Map("info", "自定义强调动画对话框", "type", "mso"),
    "AnimationCustomExitDialog", Map("info", "自定义退出动画对话框", "type", "mso"),
    "AnimationCustomPathDialog", Map("info", "自定义路径动画对话框", "type", "mso"),
    "AnimationCustomActionVerbDialog", Map("info", "自定义动作动画动词对话框", "type", "mso"),
    "EffectOptionsDialog", Map("info", "效果选项对话框", "type", "mso"),
    "AnimationCustomAddEntranceDialog", Map("info", "添加自定义入场动画", "type", "mso"),
    "AnimationCustomAddEmphasisDialog", Map("info", "添加自定义强调动画", "type", "mso"),
    "AnimationCustomAddExitDialog", Map("info", "添加自定义退出动画", "type", "mso"),
    "AnimationCustomAddPathDialog", Map("info", "添加自定义路径动画", "type", "mso"),
    "AnimationCustomAddActionVerbDlog", Map("info", "添加自定义动作动画动词", "type", "mso"),
    "AnimationCustom", Map("info", "自定义动画窗格", "type", "mso"),
    "AnimationPainter", Map("info", "动画绘图工具", "type", "mso"),
    "AnimationDuration", Map("info", "动画持续时间", "type", "mso"),
    "AnimationDelay", Map("info", "动画延迟", "type", "mso"),
    "AnimationMoveEarlier", Map("info", "提前播放动画", "type", "mso"),
    "AnimationMoveLater", Map("info", "延后播放动画", "type", "mso"),
    "SlideShowFromCurrent", Map("info", "从当前幻灯片开始播放", "type", "mso"),
    "BroadcastSlideShow", Map("info", "广播幻灯片放映", "type", "mso"),
    "BroadcastSlideShowLync", Map("info", "使用Lync广播幻灯片放映", "type", "mso"),
    "BroadcastSlideShowGeneric", Map("info", "使用通用广播幻灯片放映", "type", "mso"),
    "SlideShowSetUpDialog", Map("info", "设置幻灯片放映", "type", "mso"),
    "SlideHide", Map("info", "隐藏幻灯片", "type", "mso"),
    "SlideShowRehearseTimings", Map("info", "排练定时", "type", "mso"),
    "RecordNarrationFromCurrentSlide", Map("info", "从当前幻灯片开始录制旁白", "type", "mso"),
    "RecordNarration", Map("info", "从头开始录制旁白", "type", "mso"),
    "SlideShowPlayNarrations", Map("info", "播放幻灯片放映的旁白", "type", "mso"),
    "SlideShowUseRehearsedTimings", Map("info", "使用排练的定时进行幻灯片放映", "type", "mso"),
    "MediaControlsShow", Map("info", "显示媒体控件", "type", "mso"),
    "SlideShowUsePresenterView", Map("info", "使用演示者视图", "type", "mso"),
    "ViewThumbnailViewPowerPoint", Map("info", "查看缩略图视图", "type", "mso"),
    "ViewOutlineViewPowerPoint", Map("info", "查看大纲视图", "type", "mso"),
    "ViewSlideSorterView", Map("info", "查看幻灯片排序视图", "type", "mso"),
    "ViewNotesPageView", Map("info", "查看备注页视图", "type", "mso"),
    "ViewSlideShowReadingView", Map("info", "查看幻灯片阅读视图", "type", "mso"),
    "ViewSlideMasterView", Map("info", "查看幻灯片母版视图", "type", "mso"),
    "ViewHandoutMasterView", Map("info", "查看讲义母版视图", "type", "mso"),
    "ViewNotesMasterView", Map("info", "查看备注母版视图", "type", "mso"),
    "ViewRulerPowerPoint", Map("info", "查看标尺", "type", "mso"),
    "ViewGridlinesPowerPoint", Map("info", "查看网格线", "type", "mso"),
    "GuidesShowHide", Map("info", "显示/隐藏参考线", "type", "mso"),
    "ShowNotes", Map("info", "显示备注", "type", "mso"),
    "GridSettings", Map("info", "网格设置", "type", "mso"),
    "ViewDirectionLeftToRight", Map("info", "查看方向从左到右", "type", "mso"),
    "ViewDirectionRightToLeft", Map("info", "查看方向从右到左", "type", "mso"),
    "ZoomDialog", Map("info", "缩放对话框", "type", "mso"),
    "ZoomFitToWindow", Map("info", "缩放以适应窗口", "type", "mso"),
    "ViewDisplayInHighContrast", Map("info", "显示高对比度模式", "type", "mso"),
    "ViewDisplayInColor", Map("info", "显示彩色模式", "type", "mso"),
    "ViewDisplayInGrayscale", Map("info", "显示灰度模式", "type", "mso"),
    "ViewDisplayInPureBlackAndWhite", Map("info", "显示纯黑白模式", "type", "mso"),
    "WindowNew", Map("info", "新建窗口", "type", "mso"),
    "WindowsArrangeAll", Map("info", "排列所有窗口", "type", "mso"),
    "WindowsCascade", Map("info", "层叠窗口", "type", "mso"),
    "WindowMoveSplit", Map("info", "移动拆分窗口", "type", "mso"),
    "WindowMoreWindowsDialog", Map("info", "更多窗口对话框", "type", "mso"),
    "MacroPlay", Map("info", "播放宏", "type", "mso"),
    "VisualBasic", Map("info", "VisualBasic", "type", "mso"),
    "MacroSecurity", Map("info", "宏安全", "type", "mso"),
    "AddInManager", Map("info", "加载项管理器", "type", "mso"),
    "ComAddInsDialog", Map("info", "COM加载项对话框", "type", "mso"),
    "ActiveXLabel", Map("info", "ActiveX标签", "type", "mso"),
    "ActiveXTextBox", Map("info", "ActiveX文本框", "type", "mso"),
    "ActiveXSpinButton", Map("info", "ActiveX旋转按钮", "type", "mso"),
    "ActiveXButton", Map("info", "ActiveX按钮", "type", "mso"),
    "ActiveXImage", Map("info", "ActiveX图像", "type", "mso"),
    "ActiveXScrollBar", Map("info", "ActiveX滚动条", "type", "mso"),
    "ActiveXCheckBox", Map("info", "ActiveX复选框", "type", "mso"),
    "ActiveXRadioButton", Map("info", "ActiveX单选按钮", "type", "mso"),
    "ActiveXComboBox", Map("info", "ActiveX组合框", "type", "mso"),
    "ActiveXListBox", Map("info", "ActiveX列表框", "type", "mso"),
    "ActiveXToggleButton", Map("info", "ActiveX切换按钮", "type", "mso"),
    "MoreControlsDialog", Map("info", "更多控件对话框", "type", "mso"),
    "ControlProperties", Map("info", "控件属性", "type", "mso"),
    "ViewVisualBasicCode", Map("info", "查看VisualBasic代码", "type", "mso"),
    "SlideNew", Map("info", "新建幻灯片", "type", "mso"),
    "SlideMasterInsertLayout", Map("info", "在母版中插入版式", "type", "mso"),
    "SlideDelete", Map("info", "删除幻灯片", "type", "mso"),
    "SlideMasterRenameMaster", Map("info", "重命名母版", "type", "mso"),
    "SlideMasterPreserveMaster", Map("info", "保留母版", "type", "mso"),
    "SlideMasterMasterLayout", Map("info", "母版版式", "type", "mso"),
    "SlideMasterContentPlaceholder", Map("info", "在母版中插入内容占位符", "type", "mso"),
    "SlideMasterVerticalContentPla", Map("info", "在母版中插入垂直内容占位符", "type", "mso"),
    "SlideMasterTextPlaceholderIns", Map("info", "在母版中插入文本占位符", "type", "mso"),
    "SlideMasterVerticalTextPlaceh", Map("info", "在母版中插入垂直文本占位符", "type", "mso"),
    "SlideMasterPicturePlaceholder", Map("info", "在母版中插入图片占位符", "type", "mso"),
    "SlideMasterChartPlaceholderIn", Map("info", "在母版中插入图表占位符", "type", "mso"),
    "SlideMasterTablePlaceholderIn", Map("info", "在母版中插入表格占位符", "type", "mso"),
    "SlideMasterDiagramPlaceholder", Map("info", "在母版中插入图表占位符", "type", "mso"),
    "SlideMasterMediaPlaceholderIn", Map("info", "在母版中插入媒体占位符", "type", "mso"),
    "SlideMasterClipArtPlaceholder", Map("info", "在母版中插入剪贴画占位符", "type", "mso"),
    "SlideMasterShowTitle", Map("info", "显示母版版式标题", "type", "mso"),
    "SlideMasterShowFooters", Map("info", "显示母版版式页脚", "type", "mso"),
    "SlideBackgroundHideGraphics", Map("info", "隐藏母版版式背景图形", "type", "mso"),
    "MasterViewClose", Map("info", "关闭母版视图", "type", "mso"),
    "PasteAsHyperlink", Map("info", "作为链接粘贴", "type", "mso"),
    "PasteBitmap", Map("info", "作为Bmp粘贴", "type", "mso"),
    "PasteGif", Map("info", "作为Gif粘贴", "type", "mso"),
    "PastePng", Map("info", "作为Png粘贴", "type", "mso"),
    "PasteJpeg", Map("info", "作为Jpeg粘贴", "type", "mso"),
    "PasteTextOnly", Map("info", "仅粘贴文本", "type", "mso"),
    "PasteAsPicture", Map("info", "作为图片粘贴", "type", "mso"),
    "PasteSourceFormatting", Map("info", "使用源格式粘贴", "type", "mso"),
    "PasteDestinationTheme", Map("info", "使用目标主题粘贴", "type", "mso"),
    "ExportToVideo", Map("info", "输出为视频", "type", "mso"),
    "ShapeRectangle", Map("info", "创建矩形形状", "type", "mso"),
    "ShapeOval", Map("info", "创建椭圆形状", "type", "mso"),
    "ShapeElbowConnectorArrow", Map("info", "创建带箭头的肘形连接器形状", "type", "mso"),
    "ObjectRotateLeft90", Map("info", "向左旋转对象90度", "type", "mso"),
    "ShapeStraightConnectorArrow", Map("info", "创建带箭头的直线连接器形状", "type", "mso"),
    "ShapeElbowConnector", Map("info", "创建肘形连接器形状", "type", "mso"),
    "ObjectSetShapeDefaults", Map("info", "设置对象默认形状", "type", "mso"),
    "ShapeRoundedRectangle", Map("info", "创建圆角矩形形状", "type", "mso"),
    "ShapeStraightConnector", Map("info", "创建直线连接器形状", "type", "mso"),
    "ObjectFlipHorizontal", Map("info", "水平翻转对象", "type", "mso"),
    "ShapeRightArrow", Map("info", "创建向右箭头形状", "type", "mso"),
    "ObjectRotateFree", Map("info", "自由旋转对象", "type", "mso"),
    "ShapeDownArrow", Map("info", "创建向下箭头形状", "type", "mso"),
    "ObjectFlipVertical", Map("info", "垂直翻转对象", "type", "mso"),
    "ObjectRotateRight90", Map("info", "向右旋转对象90度", "type", "mso"),
    "ShapeRoundedRectangularCallout", Map("info", "创建圆角矩形标注形状", "type", "mso"),
    "ShapeIsoscelesTriangle", Map("info", "创建等腰三角形形状", "type", "mso"),
    "ShapesMoreShapes", Map("info", "更多形状", "type", "mso"),
    "ShapeLeftBrace", Map("info", "创建左括号形状", "type", "mso"),
    "ObjectNudgeDown", Map("info", "对象下移", "type", "mso"),
    "ShapeRightBrace", Map("info", "创建右括号形状", "type", "mso"),
    "PickUpStyle", Map("info", "拾取格式", "type", "mso"),
    "About", Map("info", "关于", "type", "mso"),

    ; --- sendinput ----------------------------------------------------------------


    "^{Home}", Map("info", "第一页", "type", "send"),
    "^{End}", Map("info", "最后一页", "type", "send"),

    "{PgUp}", Map("info", "上一页", "type", "send"),
    "{PgDn}", Map("info", "下一页", "type", "send"),

    "^{WheelUp}", Map("info", "放大字号", "type", "send"),
    "^{WheelDown}", Map("info", "缩小字号", "type", "send"),
    "+{MButton}", Map("info", "中键+Shift", "type", "send"),
    "+{LButton}", Map("info", "左键+Shift", "type", "send"),
    "!+{Tab}", Map("info", "切换应用程序", "type", "send"),
    "+#{Left}", Map("info", "将当前窗口移动到另一个桌面", "type", "send"),
    "^a", Map("info", "Ctrl+A", "type", "send"),
    "^+a", Map("info", "Ctrl+Shift+A", "type", "send"),
    "#a", Map("info", "Win+A", "type", "send"),
    "!a", Map("info", "Alt+A", "type", "send"),
    "^b", Map("info", "Ctrl+B", "type", "send"),
    "^+b", Map("info", "Ctrl+Shift+B", "type", "send"),
    "#b", Map("info", "Win+B", "type", "send"),
    "!b", Map("info", "Alt+B", "type", "send"),
    "^c", Map("info", "Ctrl+C", "type", "send"),
    "^+c", Map("info", "Ctrl+Shift+C", "type", "send"),
    "#c", Map("info", "Win+C", "type", "send"),
    "!c", Map("info", "Alt+C", "type", "send"),
    "^d", Map("info", "Ctrl+D", "type", "send"),
    "^+d", Map("info", "Ctrl+Shift+D", "type", "send"),
    "#d", Map("info", "Win+D", "type", "send"),
    "!d", Map("info", "Alt+D", "type", "send"),
    "^e", Map("info", "Ctrl+E", "type", "send"),
    "^+e", Map("info", "Ctrl+Shift+E", "type", "send"),
    "#e", Map("info", "Win+E", "type", "send"),
    "!e", Map("info", "Alt+E", "type", "send"),
    "^f", Map("info", "Ctrl+F", "type", "send"),
    "^+f", Map("info", "Ctrl+Shift+F", "type", "send"),
    "#f", Map("info", "Win+F", "type", "send"),
    "!f", Map("info", "Alt+F", "type", "send"),
    "^g", Map("info", "Ctrl+G", "type", "send"),
    "^+g", Map("info", "Ctrl+Shift+G", "type", "send"),
    "#g", Map("info", "Win+G", "type", "send"),
    "!g", Map("info", "Alt+G", "type", "send"),
    "^h", Map("info", "Ctrl+H", "type", "send"),
    "^+h", Map("info", "Ctrl+Shift+H", "type", "send"),
    "#h", Map("info", "Win+H", "type", "send"),
    "!h", Map("info", "Alt+H", "type", "send"),
    "^i", Map("info", "Ctrl+I", "type", "send"),
    "^+i", Map("info", "Ctrl+Shift+I", "type", "send"),
    "#i", Map("info", "Win+I", "type", "send"),
    "!i", Map("info", "Alt+I", "type", "send"),
    "^j", Map("info", "Ctrl+J", "type", "send"),
    "^+j", Map("info", "Ctrl+Shift+J", "type", "send"),
    "#j", Map("info", "Win+J", "type", "send"),
    "!j", Map("info", "Alt+J", "type", "send"),
    "^k", Map("info", "Ctrl+K", "type", "send"),
    "^+k", Map("info", "Ctrl+Shift+K", "type", "send"),
    "#k", Map("info", "Win+K", "type", "send"),
    "!k", Map("info", "Alt+K", "type", "send"),
    "^l", Map("info", "Ctrl+L", "type", "send"),
    "^+l", Map("info", "Ctrl+Shift+L", "type", "send"),
    "#l", Map("info", "Win+L", "type", "send"),
    "!l", Map("info", "Alt+L", "type", "send"),
    "^m", Map("info", "Ctrl+M", "type", "send"),
    "^+m", Map("info", "Ctrl+Shift+M", "type", "send"),
    "#m", Map("info", "Win+M", "type", "send"),
    "!m", Map("info", "Alt+M", "type", "send"),
    "^n", Map("info", "Ctrl+N", "type", "send"),
    "^+n", Map("info", "Ctrl+Shift+N", "type", "send"),
    "#n", Map("info", "Win+N", "type", "send"),
    "!n", Map("info", "Alt+N", "type", "send"),
    "^o", Map("info", "Ctrl+O", "type", "send"),
    "^+o", Map("info", "Ctrl+Shift+O", "type", "send"),
    "#o", Map("info", "Win+O", "type", "send"),
    "!o", Map("info", "Alt+O", "type", "send"),
    "^p", Map("info", "Ctrl+P", "type", "send"),
    "^+p", Map("info", "Ctrl+Shift+P", "type", "send"),
    "#p", Map("info", "Win+P", "type", "send"),
    "!p", Map("info", "Alt+P", "type", "send"),
    "^q", Map("info", "Ctrl+Q", "type", "send"),
    "^+q", Map("info", "Ctrl+Shift+Q", "type", "send"),
    "#q", Map("info", "Win+Q", "type", "send"),
    "!q", Map("info", "Alt+Q", "type", "send"),
    "^r", Map("info", "Ctrl+R", "type", "send"),
    "^+r", Map("info", "Ctrl+Shift+R", "type", "send"),
    "#r", Map("info", "Win+R", "type", "send"),
    "!r", Map("info", "Alt+R", "type", "send"),
    "^s", Map("info", "Ctrl+S", "type", "send"),
    "^+s", Map("info", "Ctrl+Shift+S", "type", "send"),
    "#s", Map("info", "Win+S", "type", "send"),
    "!s", Map("info", "Alt+S", "type", "send"),
    "^t", Map("info", "Ctrl+T", "type", "send"),
    "^+t", Map("info", "Ctrl+Shift+T", "type", "send"),
    "#t", Map("info", "Win+T", "type", "send"),
    "!t", Map("info", "Alt+T", "type", "send"),
    "^u", Map("info", "Ctrl+U", "type", "send"),
    "^+u", Map("info", "Ctrl+Shift+U", "type", "send"),
    "#u", Map("info", "Win+U", "type", "send"),
    "!u", Map("info", "Alt+U", "type", "send"),
    "^v", Map("info", "粘 贴", "type", "send"),
    "^+v", Map("info", "Ctrl+Shift+V", "type", "send"),
    "#v", Map("info", "Win+V", "type", "send"),
    "!v", Map("info", "Alt+V", "type", "send"),
    "^w", Map("info", "Ctrl+W", "type", "send"),
    "^+w", Map("info", "Ctrl+Shift+W", "type", "send"),
    "#w", Map("info", "Win+W", "type", "send"),
    "!w", Map("info", "Alt+W", "type", "send"),
    "^x", Map("info", "Ctrl+X", "type", "send"),
    "^+x", Map("info", "Ctrl+Shift+X", "type", "send"),
    "#x", Map("info", "Win+X", "type", "send"),
    "!x", Map("info", "Alt+X", "type", "send"),
    "^y", Map("info", "Ctrl+Y", "type", "send"),
    "^+y", Map("info", "Ctrl+Shift+Y", "type", "send"),
    "#y", Map("info", "Win+Y", "type", "send"),
    "!y", Map("info", "Alt+Y", "type", "send"),
    "^z", Map("info", "Ctrl+Z", "type", "send"),
    "^+z", Map("info", "Ctrl+Shift+Z", "type", "send"),
    "#z", Map("info", "Win+Z", "type", "send"),
    "!z", Map("info", "Alt+Z", "type", "send"),
    "^;", Map("info", "Ctrl+;", "type", "send"),
    "^+;", Map("info", "Ctrl+Shift+;", "type", "send"),
    "#;", Map("info", "Win+;", "type", "send"),
    "!;", Map("info", "Alt+;", "type", "send"),
    "{F1}", Map("info", "F1", "type", "send"),
    "{F2}", Map("info", "F2", "type", "send"),
    "{F3}", Map("info", "F3", "type", "send"),
    "{F4}", Map("info", "F4", "type", "send"),
    "{F5}", Map("info", "F5", "type", "send"),
    "{F6}", Map("info", "F6", "type", "send"),
    "{F7}", Map("info", "F7", "type", "send"),
    "{F8}", Map("info", "F8", "type", "send"),
    "{F9}", Map("info", "F9", "type", "send"),
    "{F10}", Map("info", "F10", "type", "send"),
    "{F11}", Map("info", "F11", "type", "send"),
    "^{F1}", Map("info", "Ctrl + F1", "type", "send"),
    "^{F2}", Map("info", "Ctrl + F2", "type", "send"),
    "^{F3}", Map("info", "Ctrl + F3", "type", "send"),
    "^{F4}", Map("info", "Ctrl + F4", "type", "send"),
    "^{F5}", Map("info", "Ctrl + F5", "type", "send"),
    "^{F6}", Map("info", "Ctrl + F6", "type", "send"),
    "^{F7}", Map("info", "Ctrl + F7", "type", "send"),
    "^{F8}", Map("info", "Ctrl + F8", "type", "send"),
    "^{F9}", Map("info", "Ctrl + F9", "type", "send"),
    "^{F10}", Map("info", "Ctrl + F10", "type", "send"),
    "^{F11}", Map("info", "Ctrl + F11", "type", "send"),
    "+{F1}", Map("info", "Shift + F1", "type", "send"),
    "+{F2}", Map("info", "Shift + F2", "type", "send"),
    "+{F3}", Map("info", "Shift + F3", "type", "send"),
    "+{F4}", Map("info", "Shift + F4", "type", "send"),
    "+{F5}", Map("info", "Shift + F5", "type", "send"),
    "+{F6}", Map("info", "Shift + F6", "type", "send"),
    "+{F7}", Map("info", "Shift + F7", "type", "send"),
    "+{F8}", Map("info", "Shift + F8", "type", "send"),
    "+{F9}", Map("info", "Shift + F9", "type", "send"),
    "+{F10}", Map("info", "Shift + F10", "type", "send"),
    "+{F11}", Map("info", "Shift + F11", "type", "send"),
    "!{F1}", Map("info", "Alt + F1", "type", "send"),
    "!{F2}", Map("info", "Alt + F2", "type", "send"),
    "!{F3}", Map("info", "Alt + F3", "type", "send"),
    "!{F4}", Map("info", "Alt + F4", "type", "send"),
    "!{F5}", Map("info", "Alt + F5", "type", "send"),
    "!{F6}", Map("info", "Alt + F6", "type", "send"),
    "!{F7}", Map("info", "Alt + F7", "type", "send"),
    "!{F8}", Map("info", "Alt + F8", "type", "send"),
    "!{F9}", Map("info", "Alt + F9", "type", "send"),
    "!{F10}", Map("info", "Alt + F10", "type", "send"),
    "!{F11}", Map("info", "Alt + F11", "type", "send")
)



; #endregion
