
; #region 全局变量
  
; --- AI 聊天类 ---
URL_CHATGPT     := SETTINGS["websites"]["chatgpt"]
URL_CLAUDE      := SETTINGS["websites"]["claude"]
URL_GEMINI      := SETTINGS["websites"]["gemini"]
URL_PERPLEXITY  := SETTINGS["websites"]["perplexity"]
URL_COPILOT     := SETTINGS["websites"]["copilot"]
URL_LOVART      := SETTINGS["websites"]["lovart"]

; --- 国内大模型 / 平台类 ---
URL_MINIMAX     := SETTINGS["websites"]["minimax"]
URL_TONGYI      := SETTINGS["websites"]["tongyi"]
URL_YUANBAO     := SETTINGS["websites"]["yuanbao"]
URL_DEEPSEEK    := SETTINGS["websites"]["deepseek"]
URL_WENXIN      := SETTINGS["websites"]["wenxin"]
URL_XINGHUO     := SETTINGS["websites"]["xinghuo"]
URL_ZHIPU       := SETTINGS["websites"]["zhipu"]
URL_KIMI        := SETTINGS["websites"]["kimi"]
URL_DOUBAO      := SETTINGS["websites"]["doubao"]
URL_CHATBOXAI   := SETTINGS["websites"]["chatboxai"]
URL_COZE        := SETTINGS["websites"]["coze"]

; --- 创作与设计类 ---
URL_HAILOUAI    := SETTINGS["websites"]["hailuoai"]
URL_MIDJOURNEY  := SETTINGS["websites"]["midjourney"]
URL_LEONARDO    := SETTINGS["websites"]["leonardo"]
URL_RUNWAY      := SETTINGS["websites"]["runway"]
URL_SD          := SETTINGS["websites"]["sd"]
URL_DALLE       := SETTINGS["websites"]["dalle"]
URL_IDEOGRAM    := SETTINGS["websites"]["ideogram"]
URL_FIREFLY     := SETTINGS["websites"]["firefly"]
URL_CANVA       := SETTINGS["websites"]["canva"]
URL_REMOVE_BG   := SETTINGS["websites"]["remove_bg"]
URL_UPSCALER    := SETTINGS["websites"]["upscaler"]
URL_SUNO        := SETTINGS["websites"]["suno"]
URL_UDIO        := SETTINGS["websites"]["udio"]
URL_AHK_HELP    := SETTINGS["websites"]["ahk_help"]
URL_AHK_FORUM   := SETTINGS["websites"]["ahk_forum"]
URL_OFFICE_VBA  := SETTINGS["websites"]["office_vba"]

; --- 购物生活类 ---
URL_JD          := SETTINGS["websites"]["jd"]
URL_XIANYU      := SETTINGS["websites"]["xianyu"]
URL_TAOBAO      := SETTINGS["websites"]["taobao"]

; --- 社区与问卷类 ---
URL_ZSXQ        := SETTINGS["websites"]["zsxq"]
URL_ZHYW        := SETTINGS["websites"]["zhyw"]
URL_ZHLMT       := SETTINGS["websites"]["zhlmt"]
URL_WJX         := SETTINGS["websites"]["wjx"]

; --- 视频娱乐类 ---
URL_BILIBILI    := SETTINGS["websites"]["bilibili"]
URL_IQIYI       := SETTINGS["websites"]["iqiyi"]
URL_QQLIVE      := SETTINGS["websites"]["qqlive"]
URL_XIAOHONGSHU := SETTINGS["websites"]["xiaohongshu"]
URL_DOUYIN      := SETTINGS["websites"]["douyin"]
; --- 应用程序路径常量 ---
APP_EXCEL       := SETTINGS["applications"]["excel"]
APP_BILIBILI    := SETTINGS["applications"]["bilibili"]
APP_WORD        := SETTINGS["applications"]["word"]
APP_POWERPOINT  := SETTINGS["applications"]["powerpoint"]
APP_VScode      := SETTINGS["applications"]["vscode"]
APP_SCITE       := SETTINGS["applications"]["scite"]
APP_CHROME      := SETTINGS["applications"]["chrome"]
APP_NOTEPAD     := SETTINGS["applications"]["notepad"]
APP_EVERYTHING  := SETTINGS["applications"]["everything"]
APP_7ZIP        := SETTINGS["applications"]["7zip"]
APP_TOTALCMD    := SETTINGS["applications"]["totalcmd"]
APP_POTPLAYER   := SETTINGS["applications"]["potplayer"]
APP_PHOTOSHOP   := SETTINGS["applications"]["photoshop"]
APP_EAGLE       := SETTINGS["applications"]["eagle"]
APP_FXSOUND     := SETTINGS["applications"]["fxsound"]
APP_WECHAT      := SETTINGS["applications"]["wechat"]
APP_WXWORK      := SETTINGS["applications"]["wxwork"]
APP_WMEET       := SETTINGS["applications"]["wemeet"]
APP_QQLIVE      := SETTINGS["applications"]["qqlive"]
APP_MAILMASTER  := SETTINGS["applications"]["mailmaster"]
APP_EVERNOTE    := SETTINGS["applications"]["evernote"]
APP_SNIPASTE    := SETTINGS["applications"]["snipaste"]
APP_YOUDAODICT  := SETTINGS["applications"]["youdaodict"]
APP_BAIDUNETDISK := SETTINGS["applications"]["baidunetdisk"]
APP_SPY         := SETTINGS["applications"]["spy"]
APP_NOTIFY_CREATOR := SETTINGS["applications"]["notify_creator"]
APP_XDQY        := SETTINGS["applications"]["xdqy"]
APP_DOUBAO      := SETTINGS["applications"]["doubao"]  
APP_QIANWEN      := SETTINGS["applications"]["qianwen"]  

; --- 文件路径常量 ---
FILE_PBB_SERVER      := SETTINGS["files"]["pbb_server"]
FILE_WHDJ_SERVER     := SETTINGS["files"]["maintenance_log"]
FILE_SHORTCUT_TABLE  := SETTINGS["files"]["shortcut_table"]
PATH_DOWNLOAD        := SETTINGS["path"]["download"]
PATH_BAIDU_DOWNLOAD  := SETTINGS["path"]["baidu_download"]
PATH_ROUTINE         := SETTINGS["path"]["routine"]
PATH_RCGZ            := SETTINGS["path"]["rcgz"]
PATH_INBOX           := SETTINGS["path"]["inbox"]
PATH_SYSTEM          := SETTINGS["path"]["system"]
PATH_PROJECT         := SETTINGS["path"]["project"]
PATH_DESKTOP_NOTES   := SETTINGS["path"]["desktop_notes"]
PATH_SYSTEM_DATA     := SETTINGS["path"]["system_data"]
PATH_LAYOUT_JSON     := SETTINGS["path"]["layout_json"]
PATH_PRESET_LAYOUTS_JSON := SETTINGS["path"]["preset_layouts_json"]

; --- 服务器路径常量 ---
PBB_PATH_SERVER   := SETTINGS["server_path"]["pbb_path_server"]
WH_PATH_SERVER    := SETTINGS["server_path"]["wh_path_server"]
GR_PATH_SERVER    := SETTINGS["server_path"]["gr_path_server"]

english_font := SETTINGS["system"]["english_font"]
chinese_font := SETTINGS["system"]["chinese_font"]
BOLD_english_font := SETTINGS["system"]["bold_english_font"]
BOLD_chinese_font := SETTINGS["system"]["bold_chinese_font"]


; --- 字体常量 ---

chinese_font_1 := SETTINGS["fonts"]["chinese_font_1"]
chinese_font_2 := SETTINGS["fonts"]["chinese_font_2"]
chinese_font_3 := SETTINGS["fonts"]["chinese_font_3"]
english_font_1 := SETTINGS["fonts"]["english_font_1"]
english_font_2 := SETTINGS["fonts"]["english_font_2"]
english_font_3 := SETTINGS["fonts"]["english_font_3"]


CMD_DESKTOP_NOTES_1 := SETTINGS["files"]["desktop_notes_1"]
CMD_DESKTOP_NOTES_2 := SETTINGS["files"]["desktop_notes_2"]
CMD_DESKTOP_NOTES_3 := SETTINGS["files"]["desktop_notes_3"]

chinese_font_1 := SETTINGS["fonts"]["chinese_font_1"]
chinese_font_2 := SETTINGS["fonts"]["chinese_font_2"]
chinese_font_3 := SETTINGS["fonts"]["chinese_font_3"]
chinese_font_4 := SETTINGS["fonts"]["chinese_font_4"]
chinese_font_5 := SETTINGS["fonts"]["chinese_font_5"]
chinese_font_6 := SETTINGS["fonts"]["chinese_font_6"]
chinese_font_7 := SETTINGS["fonts"]["chinese_font_7"]
chinese_font_8 := SETTINGS["fonts"]["chinese_font_8"]

english_font_1 := SETTINGS["fonts"]["english_font_1"]
english_font_2 := SETTINGS["fonts"]["english_font_2"]
english_font_3 := SETTINGS["fonts"]["english_font_3"]
english_font_4 := SETTINGS["fonts"]["english_font_4"]
english_font_5 := SETTINGS["fonts"]["english_font_5"]
english_font_6 := SETTINGS["fonts"]["english_font_6"]
english_font_7 := SETTINGS["fonts"]["english_font_7"]
english_font_8 := SETTINGS["fonts"]["english_font_8"]

english_font_ARR := [ english_font_1, english_font_2, english_font_3,
                      english_font_4, english_font_5, english_font_6,
                      english_font_7, english_font_8 ]
                      
chinese_font_ARR := [ chinese_font_1, chinese_font_2, chinese_font_3,
                      chinese_font_4, chinese_font_5, chinese_font_6,
                      chinese_font_7, chinese_font_8 ]



system_color_map := Map(
    "Black",    0x000000, ; 黑色
    "Silver",   0xC0C0C0, ; 银色
    "Gray",     0x808080, ; 灰色
    "White",    0xFFFFFF, ; 白色
    "Maroon",   0x000080, ; 栗色 (深红)
    "Red",      0x0000FF, ; 红色
    "Purple",   0x800080, ; 紫色
    "Fuchsia",  0xFF00FF, ; 品红 (洋红)
    "Green",    0x008000, ; 绿色 (深绿)
    "Lime",     0x00FF00, ; 青柠色 (亮绿)
    "Olive",    0x008080, ; 橄榄色
    "Yellow",   0x00FFFF, ; 黄色
    "Navy",     0x800000, ; 海军蓝 (深蓝)
    "Blue",     0xFF0000, ; 蓝色
    "Teal",     0x808000, ; 水鸭色 (蓝绿)
    "Aqua",     0xFFFF00  ; 水绿色 (青色)
)

color_map := Map(
    1, "22046e",
    2, "0x9b4901",
    3, "Yellow",
    4, "Green",
    5, "Aqua",
    6, "Navy",
    7, "Purple",
    8, "0c0c0c",
    9, "826d44",
    10, "7d8380"
)


TARGET_MAP := Map(
    ; --- run app ----------------------------------------------------------------
    "app_wechat", "微信",
    "app_qqlive", "腾讯视频",
    "app_wxwork", "企业微信",
    "app_wemeet", "腾讯会议",
    "APP_QIANWEN", "通义千问",
    "url_deepseek", "DeepSeek",
    "url_coze", "扣  子",
    "url_kimi", "Kimi",
    "app_doubao", "豆  包",
    "CMD_DESKTOP_NOTES_1", "VS Code 快捷键",
    "CMD_DESKTOP_NOTES_2", "CMD_DESKTOP_NOTE_2",
    "CMD_DESKTOP_NOTES_3", "CMD_DESKTOP_NOTE_3",
    "url_lovart", "Lovart",
    "url_claude", "Claude",
    "url_chatgpt", "ChatGPT",
    "url_gemini", "Gemini",
    "url_perplexity", "perplexity",
    "url_copilot", "Copilot",
    "app_everything", "Everything",
    "app_eagle", "Eagle",
    "app_evernote", "印象笔记",
    "url_zhyw", "智慧运维平台",
    "file_whdj_server", "维护登记",
    "url_zhlmt", "分发平台",
    "url_wjx", "问卷星",
    "app_vscode", "Visual Studio Code",
    "app_spy", "Window Spy",
    "FILE_SHORTCUT_TABLE", "Shortcut Table",
    "url_ahk_help", "AutoHotkey Help",
    "url_ahk_forum", "www.autohotkey.com",
    "app_notepad", "记事本",
    "app_excel", "Excel",
    "app_baidunetdisk", "百度网盘",
    "url_jd", "京  东",
    "url_xianyu", "闲  鱼",
    "url_taobao", "淘  宝",
    "app_word", "Word",
    "app_mailmaster", "网易邮箱大师",
    "app_youdaodict", "有道词典",
    "APP_BILIBILI", "哔哩哔哩",
    "URL_BILIBILI", "哔哩哔哩",
    "url_qqlive", "腾讯视频",
    "url_xiaohongshu", "小红书",
    "url_iqiyi", "爱奇艺",
    "url_douyin", "抖  音",
    "pbb_path_server", "服务器上的排班表文件夹",
    "wh_path_server", "服务器上的维护文件夹",
    "gr_path_server", "服务器上的个人文件夹",
    "do_nothing", "啥也不干",
    "do_nothing", "啥也不干",
    "do_nothing", "啥也不干",
    "do_nothing", "啥也不干",
    ; "do_nothing", "啥也不干!",
    ; "do_nothing", "啥也不干!",
    ; "do_nothing", "啥也不干!",
    ; "do_nothing", "啥也不干!",
    ; "do_nothing", "啥也不干!",

    ; --- function   ----------------------------------------------------------------

    "min_window_under_mouse", "最小化窗口",
    "func_wins", "Win+S",
    "func_ctrls", "保  存",
    "save_as", "另存为……",
    "copy_format", "复  制",
    "func_ctrlshiftw", "Ctrl+Shift+W",
    "smart_ctrlw", "Ctrl+W",
    "func_winw", "Win+W",
    "shutdown_computer", "关  机",
    "restart_computer", "重  启",
    "lock_screen", "锁 定 屏 幕",
    "close_window_under_mouse", "关闭窗口",
    "max_window", "最大化窗口",
    "left_window", "窗口靠左半边",
    "right_window", "窗口靠右半边",
    "paste_format", "粘贴格式",
    "func_wind", "显示桌面",
    "close_ppt_process", "关闭PPT进程",
    "open_current_path", "文件夹",
    "open_recycle_bin", "回收站",
    "do_nothing", "啥也不干!",
    ; "do_nothing", "啥也不干!",
    ; "do_nothing", "啥也不干!",
    ; "do_nothing", "啥也不干!",
    ; "do_nothing", "啥也不干!",
    ; "do_nothing", "啥也不干!",
    "reload_me", "Reload QWERT ?",
    "suspend_me", "Suspend QWERT ?",
    "ExitApp", "Shutdown QWERT ?",
    "func_cancel", "Cancel ?",
    "do_nothing", "啥也不干",
    "do_nothing", "啥也不干",    
    "func_ctrlx", "剪  切", 
    "add_slide_from_eagle" , "从eagle中复制PPT页面", 

    ; "show_shape_range", "显示形状",  
    ; "lock_shape_range", "锁定形状",  
    ; "unlock_shape_range", "解锁形状",  
    ; "lock_slides_shapes", "锁定形状",  
    ; "unlock_slides_shapes", "解锁形状",  
    "add_1row_slide_guides", "插入1行幻灯片参考线",  
    "add_2row_slide_guides", "插入2行幻灯片参考线",  
    "add_3row_slide_guides", "插入3行幻灯片参考线",  
    "add_4row_slide_guides", "插入4行幻灯片参考线",  

    "resize_by_guides", "resize_by_master_guides",  
    "resize_by_master_guides", "将形状集合扩展到母版参考线网格", 

    "add_default_master_guides", "插入1列母版参考线",  
    "add_2column_master_guides", "插入2列母版参考线",  
    "add_3column_master_guides", "插入3列母版参考线",  
    "add_4column_master_guides", "插入4列母版参考线",  
    "add_5column_master_guides", "插入5列母版参考线",  
    "add_6column_master_guides", "插入6列母版参考线",  

    "add_default_slide_guides", "插入1列幻灯片参考线",  
    "add_2column_slide_guides", "插入2列幻灯片参考线",  
    "add_3column_slide_guides", "插入3列幻灯片参考线",  
    "add_4column_slide_guides", "插入4列幻灯片参考线",  
    "add_5column_slide_guides", "插入5列幻灯片参考线", 
    "add_6column_slide_guides", "插入6列幻灯片参考线", 

    "delete_slide_guides", "删除幻灯片参考线",  
    "delete_master_guides", "删除母版参考线",  
    "hide_guides", "隐藏参考线",  
    "show_guides", "显示参考线",  
    "do_nothing", "啥也不干",  
    "do_nothing", "啥也不干",  
    "do_nothing", "啥也不干",  
    "do_nothing", "啥也不干",  
    "do_nothing", "啥也不干",  
    "do_nothing", "啥也不干",  
    "do_nothing", "啥也不干",  
    "do_nothing", "啥也不干",  
    "do_nothing", "啥也不干",  
    "do_nothing", "啥也不干",  
    "do_nothing", "啥也不干",  
    "do_nothing", "啥也不干",  
    "do_nothing", "啥也不干",  
    "do_nothing", "啥也不干",  
    "do_nothing", "啥也不干",  
    "do_nothing", "啥也不干",  

    ; --- hotkey   ----------------------------------------------------------------

    "!+{Tab}", "切换应用程序",
    "+#{Left}", "将当前窗口移动到另一个桌面",

    "^a", "Ctrl+A",
    "^+a", "Ctrl+Shift+A",
    "#a", "Win+A",
    "!a", "Alt+A",

    "^b", "Ctrl+B",
    "^+b", "Ctrl+Shift+B",
    "#b", "Win+B",
    "!b", "Alt+B",

    "^c", "Ctrl+C",
    "^+c", "Ctrl+Shift+C",
    "#c", "Win+C",
    "!c", "Alt+C",

    "^d", "Ctrl+D",
    "^+d", "Ctrl+Shift+D",
    "#d", "Win+D",
    "!d", "Alt+D",

    "^e", "Ctrl+E",
    "^+e", "Ctrl+Shift+E",
    "#e", "Win+E",
    "!e", "Alt+E",

    "^f", "Ctrl+F",
    "^+f", "Ctrl+Shift+F",
    "#f", "Win+F",
    "!f", "Alt+F",

    "^g", "Ctrl+G",
    "^+g", "Ctrl+Shift+G",
    "#g", "Win+G",
    "!g", "Alt+G",

    "^h", "Ctrl+H",
    "^+h", "Ctrl+Shift+H",
    "#h", "Win+H",
    "!h", "Alt+H",

    "^i", "Ctrl+I",
    "^+i", "Ctrl+Shift+I",
    "#i", "Win+I",
    "!i", "Alt+I",

    "^j", "Ctrl+J",
    "^+j", "Ctrl+Shift+J",
    "#j", "Win+J",
    "!j", "Alt+J",

    "^k", "Ctrl+K",
    "^+k", "Ctrl+Shift+K",
    "#k", "Win+K",
    "!k", "Alt+K",

    "^l", "Ctrl+L",
    "^+l", "Ctrl+Shift+L",
    "#l", "Win+L",
    "!l", "Alt+L",

    "^m", "Ctrl+M",
    "^+m", "Ctrl+Shift+M",
    "#m", "Win+M",
    "!m", "Alt+M",

    "^n", "Ctrl+N",
    "^+n", "Ctrl+Shift+N",
    "#n", "Win+N",
    "!n", "Alt+N",

    "^o", "Ctrl+O",
    "^+o", "Ctrl+Shift+O",
    "#o", "Win+O",
    "!o", "Alt+O",

    "^p", "Ctrl+P",
    "^+p", "Ctrl+Shift+P",
    "#p", "Win+P",
    "!p", "Alt+P",

    "^q", "Ctrl+Q",
    "^+q", "Ctrl+Shift+Q",
    "#q", "Win+Q",
    "!q", "Alt+Q",

    "^r", "Ctrl+R",
    "^+r", "Ctrl+Shift+R",
    "#r", "Win+R",
    "!r", "Alt+R",

    "^s", "Ctrl+S",
    "^+s", "Ctrl+Shift+S",
    "#s", "Win+S",
    "!s", "Alt+S",

    "^t", "Ctrl+T",
    "^+t", "Ctrl+Shift+T",
    "#t", "Win+T",
    "!t", "Alt+T",

    "^u", "Ctrl+U",
    "^+u", "Ctrl+Shift+U",
    "#u", "Win+U",
    "!u", "Alt+U",

    "^v", "粘  贴",
    "^+v", "Ctrl+Shift+V",
    "#v", "Win+V",
    "!v", "Alt+V",

    "^w", "Ctrl+W",
    "^+w", "Ctrl+Shift+W",
    "#w", "Win+W",
    "!w", "Alt+W",

    "^x", "Ctrl+X",
    "^+x", "Ctrl+Shift+X",
    "#x", "Win+X",
    "!x", "Alt+X",

    "^y", "Ctrl+Y",
    "^+y", "Ctrl+Shift+Y",
    "#y", "Win+Y",
    "!y", "Alt+Y",

    "^z", "Ctrl+Z",
    "^+z", "Ctrl+Shift+Z",
    "#z", "Win+Z",
    "!z", "Alt+Z",

    "^;", "Ctrl+;",
    "^+;", "Ctrl+Shift+;",
    "#;", "Win+;",
    "!;", "Alt+;",

    "{F1}", "F1", 
    "{F2}", "F2", 
    "{F3}", "F3", 
    "{F4}", "F4", 
    "{F5}", "F5", 
    "{F6}", "F6", 
    "{F7}", "F7", 
    "{F8}", "F8", 
    "{F9}", "F9", 
    "{F10}", "F10", 
    "{F11}", "F11", 

    "^{F1}", "Ctrl + F1", 
    "^{F2}", "Ctrl + F2", 
    "^{F3}", "Ctrl + F3", 
    "^{F4}", "Ctrl + F4", 
    "^{F5}", "Ctrl + F5",   
    "^{F6}", "Ctrl + F6", 
    "^{F7}", "Ctrl + F7", 
    "^{F8}", "Ctrl + F8", 
    "^{F9}", "Ctrl + F9", 
    "^{F10}", "Ctrl + F10", 
    "^{F11}", "Ctrl + F11", 

    "+{F1}", "Shift + F1", 
    "+{F2}", "Shift + F2", 
    "+{F3}", "Shift + F3", 
    "+{F4}", "Shift + F4", 
    "+{F5}", "Shift + F5", 
    "+{F6}", "Shift + F6", 
    "+{F7}", "Shift + F7", 
    "+{F8}", "Shift + F8", 
    "+{F9}", "Shift + F9", 
    "+{F10}", "Shift + F10", 
    "+{F11}", "Shift + F11", 

    "!{F1}", "Alt + F1", 
    "!{F2}", "Alt + F2", 
    "!{F3}", "Alt + F3", 
    "!{F4}", "Alt + F4", 
    "!{F5}", "Alt + F5", 
    "!{F6}", "Alt + F6", 
    "!{F7}", "Alt + F7", 
    "!{F8}", "Alt + F8", 
    "!{F9}", "Alt + F9", 
    "!{F10}", "Alt + F10", 
    "!{F11}", "Alt + F11",

    ; --- ppt control   ----------------------------------------------------------------
 
    ; --- 对齐 (Align) ---
    "ObjectsAlignLeftSmart", "左对齐",
    "ObjectsAlignCenterHorizontalSmart", "水平居中",
    "ObjectsAlignRightSmart", "右对齐",
    "ObjectsAlignTopSmart", "顶部对齐",
    "ObjectsAlignMiddleVerticalSmart", "垂直居中",
    "ObjectsAlignBottomSmart", "底部对齐",
    "AlignObjects", "对齐对象菜单", ; 弹出对齐菜单
    
    ; --- 分布 (Distribute) ---
    "ObjectsDistributeLeft", "横向分布",
    "ObjectsDistributeCenter", "横向居中分布",
    "ObjectsDistributeRight", "横向右分布",
    "ObjectsDistributeTop", "纵向分布",
    "ObjectsDistributeMiddle", "纵向居中分布",
    "ObjectsDistributeBottom", "纵向下分布",

    ; --- 图层顺序 (Order) ---
    "ObjectSendToBack", "置于底层",
    "ObjectBringToFront", "置于顶层",
    "ObjectSendBackward", "下移一层",
    "ObjectBringForward", "上移一层",
    "SelectionPane", "选择窗格", ; 打开选择窗格以管理图层

    ; --- 组合 (Grouping) ---
    "GroupShapes", "组合",
    "UngroupShapes", "取消组合",
    "RegroupShapes", "重新组合",

    ; --- 旋转与翻转 (Rotate & Flip) ---
    "RotateRight", "向右旋转90度",
    "RotateLeft", "向左旋转90度",
    "RotateFlipHorizontal", "水平翻转",
    "RotateFlipVertical", "垂直翻转",
    "RotateFlipHorizontalFlipVertical", "水平垂直翻转", ; 180度
    "RotateFlipHorizontalRotate90Right", "右旋+水平翻转",
    "RotateFlipVerticalRotate90Right", "右旋+垂直翻转",

    ; --- 形状编辑 (Edit Shape) ---
    "EditShape", "编辑顶点",
    "ChangeShape", "更改形状",
    "InkToShape", "墨迹转换为形状",
    "ConvertToFreeform", "转换为自由曲线",

    ; --- 文本与段落 (Text & Paragraph) ---
    "AlignTextLeft", "文本左对齐",
    "AlignTextCenter", "文本居中",
    "AlignTextRight", "文本右对齐",
    "AlignTextJustify", "文本两端对齐",
    "AlignTextDistribute", "文本分散对齐",
    "JustifyLow", "文本低对齐",
    "AlignTextTop", "文本顶端对齐",
    "AlignTextMiddle", "文本中部对齐",
    "AlignTextBottom", "文本底端对齐",
    "TextDirectionRotate270Normal", "文字方向：竖排",
    "TextDirectionRotate90Normal", "文字方向：竖排(反向)",
    "TextDirectionHorizontal", "文字方向：横排",
    "Bullets", "项目符号",
    "Numbering", "编号",
    "LineSpacing", "行距",
    "IncreaseIndent", "增加缩进",
    "DecreaseIndent", "减少缩进",
    "HangingIndent", "悬挂缩进",
    "Font", "字体设置",
    "FontSize", "字号",
    "FontSizeGrow", "增大字号",
    "FontSizeShrink", "减小字号",
    "Bold", "加粗",
    "Italic", "倾斜",
    "Underline", "下划线",
    "Shadow", "阴影",
    "Strikethrough", "删除线",
    "ChangeCase", "更改大小写",
    "Subscript", "下标",
    "Superscript", "上标",
    "ClearFormatting", "清除格式",
    "Highlight", "文本高亮",
    "FontColor", "字体颜色",

    ; --- 形状样式 (Shape Styles) ---
    "ShapeFillColorPicker", "形状填充",
    "ShapeOutlineColorPicker", "形状轮廓",
    "ShapeEffects", "形状效果",
    "QuickStylesGallery", "快速样式",
    "LineStyle", "线条样式",
    "LineWeight", "线条粗细",
    "LineDashes", "虚线线型",
    "LineArrowheads", "箭头样式",

    ; --- 图片工具 (Picture Tools) ---
    "PictureChange", "更改图片",
    "PictureReset", "重设图片",
    "Crop", "裁剪",
    "CropToShape", "裁剪为形状",
    "AspectRatio", "纵横比",
    "CompressPictures", "压缩图片",
    "PictureColor", "图片颜色",
    "PictureArtisticEffects", "艺术效果",
    "PictureCorrections", "图片更正",
    "PictureBorder", "图片边框",
    "RemoveBackground", "删除背景",
    "OnlinePicture", "联机图片",
    "InsertScreenshot", "屏幕截图",
    "PictureCropAspectRatio1To1", "图片裁剪宽高比1:1",
    "PictureCropAspectRatio2To3", "图片裁剪宽高比2:3",
    "PictureCropAspectRatio3To4", "图片裁剪宽高比3:4",
    "PictureCropAspectRatio3To5", "图片裁剪宽高比3:5",
    "PictureCropAspectRatio4To5", "图片裁剪宽高比4:5",
    "PictureCropAspectRatio3To2", "图片裁剪宽高比3:2",
    "PictureCropAspectRatio4To3", "图片裁剪宽高比4:3",
    "PictureCropAspectRatio5To3", "图片裁剪宽高比5:3",
    "PictureCropAspectRatio5To4", "图片裁剪宽高比5:4",
    "PictureCropAspectRatio16To9", "图片裁剪宽高比16:9",
    "PictureCropAspectRatio16To10", "图片裁剪宽高比16:10",
    "PictureFillCrop", "图片填充裁剪",
    "PictureFitCrop", "图片适应裁剪",



    ; --- 排列与位置 (Arrange & Position) ---
    "NudgeUp", "向上微调",
    "NudgeDown", "向下微调",
    "NudgeLeft", "向左微调",
    "NudgeRight", "向右微调",
    "SizeUp", "向上增大",
    "SizeDown", "向下减小",
    "SizeLeft", "向左增大",
    "SizeRight", "向右减小",
    "SizeObjectDialog", "大小和位置", ; 打开详细设置面板
    "SnapToGrid", "对齐网格",
    "SnapToShapes", "对齐对象",
    "Gridlines", "网格线",
    "Guides", "参考线",
    "ViewZoom", "缩放",
    "FitToWindow", "适应窗口大小",
    "ZoomToSelection", "缩放至所选内容",

    ; --- 表格工具 (Table Tools - 选中表格时) ---
    "InsertRowsAbove", "在上方插入行",
    "InsertRowsBelow", "在下方插入行",
    "InsertColumnsLeft", "在左侧插入列",
    "InsertColumnsRight", "在右侧插入列",
    "DeleteRows", "删除行",
    "DeleteColumns", "删除列",
    "MergeCells", "合并单元格",
    "SplitCells", "拆分单元格",
    "DistributeRows", "平均分布各行",
    "DistributeColumns", "平均分布各列",
    "TableBorders", "边框",
    "TableFillColor", "底纹",

    ; --- 图表工具 (Chart Tools - 选中图表时) ---
    "ChartType", "更改图表类型",
    "ChartData", "编辑数据",
    "ChartLayout", "图表布局",
    "ChartStyles", "图表样式",
    "ChartAxes", "坐标轴",
    "ChartGridlines", "网格线",
    "ChartLegend", "图例",
    "ChartDataLabels", "数据标签",
    "ChartTrendline", "趋势线",

    ; --- 智能艺术图形 (SmartArt) ---
    "SmartArtAddShapeAfter", "添加形状(后)",
    "SmartArtAddShapeBefore", "添加形状(前)",
    "SmartArtAddShapeAbove", "添加形状(上)",
    "SmartArtAddShapeBelow", "添加形状(下)",
    "SmartArtChangeHierarchy", "更改层次结构",
    "SmartArtRTL", "从右向左",
    "SmartArtLarger", "增大",
    "SmartArtSmaller", "减小",
    "SmartArtReset", "重设",

    ; --- 其他常用 ---
    "HyperlinkInsert", "插入超链接",
    "Duplicate", "复制选中对象", ; 相当于 Ctrl+D
    "Delete", "删除",
    "Copy", "复制",
    "Paste", "粘贴",
    "PasteSourceFormatting", "保留源格式粘贴",
    "PasteMergeFormatting", "合并格式粘贴",
    "PastePicture", "粘贴为图片",
    "Save", "保存",
    "Undo", "撤销",
    "Redo", "恢复",
    "SelectAll", "全选",
    "Find", "查找",
    "Replace", "替换",

    "AutoSaveSwitch",               "自动保存到OneDriver",
    "FileNewDefault",               "新建默认文件",
    "FileOpenUsingBackstage",       "利用后台视图打开文件",
    "FileSave",                     "保存文件",
    "FileSendAsAttachment",         "当作附件发送",
    "FilePrintQuick",               "快速打印",
    "PrintPreviewAndPrint",         "打印预览",
    "Spelling",                     "拼写检查",
    "RedoOrRepeat",                 "重做",
    "SlideShowFromBeginning",       "从头开始播放幻灯片放映",
    "Paste",                        "粘贴",
    "PasteSpecialDialog",           "粘贴特殊对话框",
    "Cut",                          "剪切",
    "Copy",                         "复制",
    "PasteDuplicate",               "复制并粘贴",
    "FormatPainter",                "格式刷",
    "ShowClipboard",                "显示剪贴板",
    "DuplicateSelectedSlides",      "复制所选幻灯片",
    "SlidesFromOutline",            "从大纲生成幻灯片",
    "SlidesReuseSlides",            "重用幻灯片",
    "SlideReset",                   "重置幻灯片",
    "SectionAdd",                   "添加分区",
    "SectionRename",                "重命名分区",
    "SectionMergeWithPrevious",     "合并到前一个分区",
    "SectionRemoveAll",             "移除所有分区",
    "SectionCollapseAll",           "折叠所有分区",
    "SectionExpandAll",             "展开所有分区",
    "FontSizeIncrease",             "字体大小增加",
    "FontSizeDecrease",             "字体大小减少",
    "ClearFormatting",              "清除格式",
    "Bold",                         "加粗",
    "Italic",                       "斜体",
    "Underline",                    "下划线",
    "Shadow",                       "阴影",
    "Strikethrough",                "删除线",
    "FontColorMoreColorsDialogPowerPoint", "字体颜色对话框",
    "EyedropperFillText",           "填充文本取色器",
    "FontDialogPowerPoint",         "字体对话框",
    "BulletsAndNumberingBulletsDialog", "着重号对话框",
    "BulletsAndNumberingNumberingDialog", "编号对话框",
    "IndentDecrease",               "缩进减少",
    "IndentIncrease",               "缩进增加",
    "AlignLeft",                    "居左对齐",
    "AlignCenter",                  "居中对齐",
    "AlignRight",                   "居右对齐",
    "AlignJustify",                 "两端对齐",
    "AlignJustifyWithMixedLanguages", "带多种语言的两端对齐",
    "AlignJustifyLow",              "低层次两端对齐",
    "ParagraphDistributed",         "分散对齐",
    "AlignJustifyThai",             "带泰语的两端对齐",
    "TextDirectionLeftToRight",     "文字方向-从左到右",
    "TextDirectionRightToLeft",     "文字方向-从右到左",
    "ParagraphMoreColumnsDialog",   "段落-更多栏",
    "TextDirectionMoreOptionsDialog", "文本方向更多选项-对话框",
    "TextAlignMoreOptionsDialog",   "对齐-更多选项",
    "ConvertToSmartArtMoreSmartArtGraphicsDialog", "转换为智能图形-更多智能图形",
    "PowerPointParagraphDialog",    "幻灯片段落-对话框",
    "ObjectBringToFront",           "对象-置于顶层",
    "ObjectSendToBack",             "对象-置于底层",
    "ObjectBringForward",           "对象-上移一层",
    "ObjectSendBackward",           "对象-下移一层",
    "ObjectsGroup",                 "对象-组合",
    "ObjectsUngroup",               "对象-取消组合",
    "ObjectsRegroup",               "对象-重新组合",
    "ObjectsAlignLeftSmart",        "对象-智能对齐-居左",
    "ObjectsAlignCenterHorizontalSmart", "对象-智能对齐-居中水平",
    "ObjectsAlignRightSmart",       "对象-智能对齐-居右",
    "ObjectsAlignTopSmart",         "对象-智能对齐-居上",
    "ObjectsAlignMiddleVerticalSmart", "对象-智能对齐-居中垂直",
    "ObjectsAlignBottomSmart",      "对象-智能对齐-居下",
    "AlignDistributeHorizontally",  "对齐-水平分布",
    "AlignDistributeVertically",    "对齐-垂直分布",
    "ObjectsAlignRelativeToContainerSmart", "对象-相对于容器对齐",
    "ObjectsAlignSelectedSmart",    "对象-对齐所选项",
    "ObjectRotationOptionsDialog",  "对象-旋转选项-对话框",
    "SelectionPane",                "选择窗格",
    "ObjectFillMoreColorsDialog",   "对象-填充-更多颜色",
    "EyedropperFill",               "取色器-填充",
    "ObjectPictureFill",            "对象-图片填充",
    "ShapeFillMoreGradientsDialog", "形状-填充-更多渐变",
    "MoreTextureOptions",           "更多纹理选项",
    "ObjectBorderOutlineColorMoreColorsDialog", "对象-边框/外框颜色-更多颜色",
    "EyedropperOutline",            "取色器-外框",
    "LineStylesDialog",             "线条样式-对话框",
    "ArrowsMore",                   "更多箭头",
    "_3DBevelOptionsDialog",        "3D斜角选项-对话框",
    "ShadowOptionsDialog",          "阴影选项对话框",
    "ReflectionsMoreOptions",       "反射选项对话框",
    "GlowColorMoreColorsDialog",    "光晕颜色对话框",
    "EyedropperGlow",               "取色器-光晕",
    "GlowsMoreOptions",             "光晕-更多选项",
    "SoftEdgesMoreOptions",         "柔化边缘-更多选项",
    "_3DRotationOptionsDialog",     "3D旋转选项-对话框",
    "ObjectFormatDialog",           "对象格式对话框",
    "FindDialog",                   "查找对话框",
    "ReplaceDialog",                "替换对话框",
    "FontsReplaceFonts",            "替换字对话框",
    "SelectAll",                    "全选",
    "Dictate",                      "听写",
    "TableInsert",                  "插入表格",
    "TableDrawTable",               "绘制表格",
    "ExcelSpreadsheetInsert",       "插入Excel电子表格",
    "PictureInsertFromFilePowerPoint", "从文件插入图片",
    "ClipArtInsertDialog",          "插入剪贴画对话框",
    "ScreenClipping",               "屏幕剪辑",
    "PhotoAlbumInsert",             "插入相册",
    "PhotoAlbumEdit",               "编辑相册",
    "IconInsertFromFile",           "从文件插入图标",
    "Insert3DModelFallback",        "插入3D模型备用",
    "Insert3DModelDefault",        "插入默认3D模型",
    "Insert3DModelFromFile",        "从文件插入3D模型",
    "Insert3DModelFromOnline",      "从在线插入3D模型",
    "SmartArtInsert",               "插入智能图形",
    "ChartInsert",                  "插入图表",
    "OfficeExtensionsAppStore",     "应用商店",
    "OfficeExtensionsDialog",       "扩展对话框",
    "OfficeExtensionsManageOtherAddins", "管理加载项",
    "MSPPTInsertTableofContents",   "插入摘要缩放定位",
    "SectionZoomInsert",            "插入节缩放定位",
    "SlideZoomInsert",              "插入幻灯片缩放定位",
    "HyperlinkInsert",              "插入超链接",
    "ActionInsert",                 "插入动作",
    "InsertNewComment",             "插入新批注",
    "TextBoxInsert",                "插入文本框",
    "TextBoxInsertHorizontal",      "插入横向文本框",
    "TextBoxInsertVertical",        "插入纵向文本框",
    "HeaderFooterInsert",           "插入页眉页脚",
    "DateAndTimeInsert",            "插入日期和时间",
    "NumberInsert",                 "插入数字",
    "OleObjectctInsert",            "插入OLE对象",
    "EquationInsertNew",            "插入数学公式",
    "InkEquation",                  "手写公式",
    "SymbolInsert",                 "插入符号",
    "MovieFromClipOrganizerInsert", "从剪贴画库插入影片",
    "MovieFromFileInsert",          "从文件插入影片",
    "SoundInsertFromFile",          "从文件插入声音",
    "SoundRecord",                  "录制声音",
    "ObjectScreenRecording",        "屏幕录制",
    "InsertMSForms",                "插入MS表单",
    "FingerPaintingMode",           "通过触摸绘制",
    "InkEraser",                    "笔划橡皮擦",
    "PointEraser",                  "点状橡皮擦",
    "SegmentEraser",                "线段橡皮擦",
    "ShowRulerStencil",             "显示标尺",
    "InkToTextAnalysis",            "将墨迹转换为文本",
    "InkToShapeAnalysis",           "将墨迹转换为形状",
    "InkToMathAnalysis",            "将墨迹转换为数学公式",
    "MathInputEditor",              "墨迹公式编辑器",
    "Replay",                       "墨迹重播",
    "ThemeSearchOfficeOnlinePowerPoint", "启动在线主题搜索",
    "ThemeBrowseForThemesPowerPoint", "浏览并选择主题",
    "ThemeSaveCurrentPowerPoint",   "保存当前主题",
    "ThemeColorsCreateNew",         "创建新的主题颜色",
    "ThemeColorsReset",             "重置主题颜色",
    "ThemeFontsCreateNew",          "创建新的主题字体",
    "SlideBackgroundFormatDialog",  "幻灯片背景格式对话框",
    "SlideBackgroundReset",         "重置幻灯片背景",
    "CustomSlideSize",              "自定义幻灯片大小",
    "LaunchFormatBackground",       "启动格式背景对话框",
    "DesignerPane",                 "设计窗格",
    "TransitionPreview",            "过渡效果预览",
    "TransitionSoundLoopUntilNextSound", "过渡声音循环直到下一个声音",
    "TransitionDuration",           "过渡持续时间",
    "SlideTransitionApplyToAll",    "将过渡应用于所有幻灯片",
    "SlideTransitionOnMouseClick",  "单击鼠标时换片",
    "SlideTransitionAutomaticallyAfter", "自动换片",
    "AnimationPreview",             "动画预览",
    "AnimationAutoPreview",         "自动动画预览",
    "AnimationCustomEntranceDialog", "自定义入场动画对话框",
    "AnimationCustomEmphasisDialog", "自定义强调动画对话框",
    "AnimationCustomExitDialog",    "自定义退出动画对话框",
    "AnimationCustomPathDialog",    "自定义路径动画对话框",
    "AnimationCustomActionVerbDialog", "自定义动作动画动词对话框",
    "EffectOptionsDialog",          "效果选项对话框",
    "AnimationCustomAddEntranceDialog", "添加自定义入场动画",
    "AnimationCustomAddEmphasisDialog", "添加自定义强调动画",
    "AnimationCustomAddExitDialog", "添加自定义退出动画",
    "AnimationCustomAddPathDialog", "添加自定义路径动画",
    "AnimationCustomAddActionVerbDlog", "添加自定义动作动画动词",
    "AnimationCustom",              "自定义动画窗格",
    "AnimationPainter",             "动画绘图工具",
    "AnimationDuration",            "动画持续时间",
    "AnimationDelay",               "动画延迟",
    "AnimationMoveEarlier",         "提前播放动画",
    "AnimationMoveLater",           "延后播放动画",
    "SlideShowFromCurrent",         "从当前幻灯片开始播放",
    "BroadcastSlideShow",           "广播幻灯片放映",
    "BroadcastSlideShowLync",       "使用Lync广播幻灯片放映",
    "BroadcastSlideShowGeneric",    "使用通用广播幻灯片放映",
    "SlideShowSetUpDialog",         "设置幻灯片放映",
    "SlideHide",                    "隐藏幻灯片",
    "SlideShowRehearseTimings",     "排练定时",
    "RecordNarrationFromCurrentSlide", "从当前幻灯片开始录制旁白",
    "RecordNarration",              "从头开始录制旁白",
    "SlideShowPlayNarrations",      "播放幻灯片放映的旁白",
    "SlideShowUseRehearsedTimings", "使用排练的定时进行幻灯片放映",
    "MediaControlsShow",            "显示媒体控件",
    "SlideShowUsePresenterView",    "使用演示者视图",
    "ViewThumbnailViewPowerPoint",  "查看缩略图视图",
    "ViewOutlineViewPowerPoint",    "查看大纲视图",
    "ViewSlideSorterView",          "查看幻灯片排序视图",
    "ViewNotesPageView",            "查看备注页视图",
    "ViewSlideShowReadingView",     "查看幻灯片阅读视图",
    "ViewSlideMasterView",          "查看幻灯片母版视图",
    "ViewHandoutMasterView",        "查看讲义母版视图",
    "ViewNotesMasterView",          "查看备注母版视图",
    "ViewRulerPowerPoint",          "查看标尺",
    "ViewGridlinesPowerPoint",      "查看网格线",
    "GuidesShowHide",               "显示/隐藏参考线",
    "ShowNotes",                    "显示备注",
    "GridSettings",                 "网格设置",
    "ViewDirectionLeftToRight",     "查看方向从左到右",
    "ViewDirectionRightToLeft",     "查看方向从右到左",
    "ZoomDialog",                   "缩放对话框",
    "ZoomFitToWindow",              "缩放以适应窗口",
    "ViewDisplayInHighContrast",    "显示高对比度模式",
    "ViewDisplayInColor",           "显示彩色模式",
    "ViewDisplayInGrayscale",       "显示灰度模式",
    "ViewDisplayInPureBlackAndWhite", "显示纯黑白模式",
    "WindowNew",                    "新建窗口",
    "WindowsArrangeAll",            "排列所有窗口",
    "WindowsCascade",               "层叠窗口",
    "WindowMoveSplit",              "移动拆分窗口",
    "WindowMoreWindowsDialog",      "更多窗口对话框",
    "MacroPlay",                    "播放宏",
    "VisualBasic",                  "VisualBasic",
    "MacroSecurity",                "宏安全",
    "AddInManager",                 "加载项管理器",
    "ComAddInsDialog",              "COM加载项对话框",
    "ActiveXLabel",                 "ActiveX标签",
    "ActiveXTextBox",               "ActiveX文本框",
    "ActiveXSpinButton",            "ActiveX旋转按钮",
    "ActiveXButton",                "ActiveX按钮",
    "ActiveXImage",                 "ActiveX图像",
    "ActiveXScrollBar",             "ActiveX滚动条",
    "ActiveXCheckBox",              "ActiveX复选框",
    "ActiveXRadioButton",           "ActiveX单选按钮",
    "ActiveXComboBox",              "ActiveX组合框",
    "ActiveXListBox",               "ActiveX列表框",
    "ActiveXToggleButton",          "ActiveX切换按钮",
    "MoreControlsDialog",           "更多控件对话框",
    "ControlProperties",            "控件属性",
    "ViewVisualBasicCode",          "查看VisualBasic代码",
    "SlideNew",                     "新建幻灯片",
    "SlideMasterInsertLayout",      "在母版中插入版式",
    "SlideDelete",                  "删除幻灯片",
    "SlideMasterRenameMaster",      "重命名母版",
    "SlideMasterPreserveMaster",    "保留母版",
    "SlideMasterMasterLayout",      "母版版式",
    "SlideMasterContentPlaceholder", "在母版中插入内容占位符",
    "SlideMasterVerticalContentPla", "在母版中插入垂直内容占位符",
    "SlideMasterTextPlaceholderIns", "在母版中插入文本占位符",
    "SlideMasterVerticalTextPlaceh", "在母版中插入垂直文本占位符",
    "SlideMasterPicturePlaceholder", "在母版中插入图片占位符",
    "SlideMasterChartPlaceholderIn", "在母版中插入图表占位符",
    "SlideMasterTablePlaceholderIn", "在母版中插入表格占位符",
    "SlideMasterDiagramPlaceholder", "在母版中插入图表占位符",
    "SlideMasterMediaPlaceholderIn", "在母版中插入媒体占位符",
    "SlideMasterClipArtPlaceholder", "在母版中插入剪贴画占位符",
    "SlideMasterShowTitle",         "显示母版版式标题",
    "SlideMasterShowFooters",       "显示母版版式页脚",
    "SlideBackgroundHideGraphics",  "隐藏母版版式背景图形",
    "MasterViewClose",              "关闭母版视图",
    "PasteAsHyperlink",             "作为链接粘贴",
    "PasteBitmap",                  "作为Bmp粘贴",
    "PasteGif",                     "作为Gif粘贴",
    "PastePng",                     "作为Png粘贴",
    "PasteJpeg",                    "作为Jpeg粘贴",
    "PasteTextOnly",                "仅粘贴文本",
    "PasteAsPicture",               "作为图片粘贴",
    "PasteSourceFormatting",        "使用源格式粘贴",
    "PasteDestinationTheme",        "使用目标主题粘贴",
    "ExportToVideo",                "输出为视频",
    "ShapeRectangle",               "创建矩形形状",
    "ShapeOval",                    "创建椭圆形状",
    "ShapeElbowConnectorArrow",     "创建带箭头的肘形连接器形状",
    "ObjectRotateLeft90",           "向左旋转对象90度",
    "ShapeStraightConnectorArrow",  "创建带箭头的直线连接器形状",
    "ShapeElbowConnector",          "创建肘形连接器形状",
    "ObjectSetShapeDefaults",       "设置对象默认形状",
    "ShapeRoundedRectangle",        "创建圆角矩形形状",
    "ShapeStraightConnector",       "创建直线连接器形状",
    "ObjectFlipHorizontal",         "水平翻转对象",
    "ShapeRightArrow",              "创建向右箭头形状",
    "ObjectRotateFree",             "自由旋转对象",
    "ShapeDownArrow",               "创建向下箭头形状",
    "ObjectFlipVertical",           "垂直翻转对象",
    "ObjectRotateRight90",          "向右旋转对象90度",
    "ShapeRoundedRectangularCallout", "创建圆角矩形标注形状",
    "ShapeIsoscelesTriangle",       "创建等腰三角形形状",
    "ShapesMoreShapes",             "更多形状",
    "ShapeLeftBrace",               "创建左括号形状",
    "ObjectNudgeDown",              "对象下移",
    "ShapeRightBrace",              "创建右括号形状",
    "PickUpStyle",                  "拾取格式",
    "About",                        "关于"
)

TARGET_TYPE_MAP := Map(
    ; --- run app ----------------------------------------------------------------
    "app_wechat", "run",
    "app_qqlive", "run",
    "app_wxwork", "run",
    "app_wemeet", "run",
    "APP_QIANWEN", "run",
    "url_deepseek", "run",
    "url_coze", "run",
    "url_kimi", "run",
    "app_doubao", "run",
    "CMD_DESKTOP_NOTES_1", "run",
    "CMD_DESKTOP_NOTES_2", "run",
    "CMD_DESKTOP_NOTES_3", "run",
    "url_lovart", "run",
    "url_claude", "run",
    "url_chatgpt", "run",
    "url_gemini", "run",
    "url_perplexity", "run",
    "url_copilot", "run",
    "app_everything", "run",
    "app_eagle", "run",
    "app_evernote", "run",
    "url_zhyw", "run",
    "file_whdj_server", "run",
    "url_zhlmt", "run",
    "url_wjx", "run",
    "app_vscode", "run",
    "app_spy", "run",
    "FILE_SHORTCUT_TABLE", "run",
    "url_ahk_help", "run",
    "url_ahk_forum", "run",
    "app_notepad", "run",
    "app_excel", "run",
    "app_baidunetdisk", "run",
    "url_jd", "run",
    "url_xianyu", "run",
    "url_taobao", "run",
    "app_word", "run",
    "app_mailmaster", "run",
    "app_youdaodict", "run",
    "APP_BILIBILI", "run",
    "URL_BILIBILI", "run",
    "url_xiaohongshu", "run",
    "url_iqiyi", "run",
    "url_douyin", "run",
    "pbb_path_server", "run",
    "wh_path_server", "run",
    "gr_path_server", "run",

    ; --- func ----------------------------------------------------------------

    "min_window_under_mouse", "func",
    "func_ctrlx", "func",
    "func_wins", "func",
    "func_ctrls", "func",
    "save_as", "func",
    "copy_format", "func",
    "func_ctrlshiftw", "func",
    "smart_ctrlw", "func",
    "func_winw", "func",
    "shutdown_computer", "func",
    "restart_computer", "func",
    "lock_screen", "func",
    "close_window_under_mouse", "func",
    "max_window", "func",
    "left_window", "func",
    "right_window", "func",
    "paste_format", "func",
    "func_wind", "func",
    "close_ppt_process", "func",
    "open_current_path", "func",
    "open_recycle_bin", "func",
    "do_nothing", "func",


    ; --- mso ----------------------------------------------------------------
    ; --- 对齐 (Align) -----------
    "ObjectsAlignLeftSmart", "mso",
    "ObjectsAlignCenterHorizontalSmart", "mso",
    "ObjectsAlignRightSmart", "mso",
    "ObjectsAlignTopSmart", "mso",
    "ObjectsAlignMiddleVerticalSmart", "mso",
    "ObjectsAlignBottomSmart", "mso",
    "AlignObjects", "mso",

    ; --- 分布 (Distribute) ---
    "ObjectsDistributeLeft", "mso",
    "ObjectsDistributeCenter", "mso",
    "ObjectsDistributeRight", "mso",
    "ObjectsDistributeTop", "mso",
    "ObjectsDistributeMiddle", "mso",
    "ObjectsDistributeBottom", "mso",

    ; --- 图层顺序 (Order) ---
    "ObjectSendToBack", "mso",
    "ObjectBringToFront", "mso",
    "ObjectSendBackward", "mso",
    "ObjectBringForward", "mso",
    "SelectionPane", "mso",

    ; --- 组合 (Grouping) ---
    "GroupShapes", "mso",
    "UngroupShapes", "mso",
    "RegroupShapes", "mso",

    ; --- 旋转与翻转 (Rotate & Flip) ---
    "RotateRight", "mso",
    "RotateLeft", "mso",
    "RotateFlipHorizontal", "mso",
    "RotateFlipVertical", "mso",
    "RotateFlipHorizontalFlipVertical", "mso",
    "RotateFlipHorizontalRotate90Right", "mso",
    "RotateFlipVerticalRotate90Right", "mso",

    ; --- 形状编辑 (Edit Shape) ---
    "EditShape", "mso",
    "ChangeShape", "mso",
    "InkToShape", "mso",
    "ConvertToFreeform", "mso",

    ; --- 文本与段落 (Text & Paragraph) ---
    "AlignTextLeft", "mso",
    "AlignTextCenter", "mso",
    "AlignTextRight", "mso",
    "AlignTextJustify", "mso",
    "AlignTextDistribute", "mso",
    "JustifyLow", "mso",
    "AlignTextTop", "mso",
    "AlignTextMiddle", "mso",
    "AlignTextBottom", "mso",
    "TextDirectionRotate270Normal", "mso",
    "TextDirectionRotate90Normal", "mso",
    "TextDirectionHorizontal", "mso",
    "Bullets", "mso",
    "Numbering", "mso",
    "LineSpacing", "mso",
    "IncreaseIndent", "mso",
    "DecreaseIndent", "mso",
    "HangingIndent", "mso",
    "Font", "mso",
    "FontSize", "mso",
    "FontSizeGrow", "mso",
    "FontSizeShrink", "mso",
    "Bold", "mso",
    "Italic", "mso",
    "Underline", "mso",
    "Shadow", "mso",
    "Strikethrough", "mso",
    "ChangeCase", "mso",
    "Subscript", "mso",
    "Superscript", "mso",
    "ClearFormatting", "mso",
    "Highlight", "mso",
    "FontColor", "mso",

    ; --- 形状样式 (Shape Styles) ---
    "ShapeFillColorPicker", "mso",
    "ShapeOutlineColorPicker", "mso",
    "ShapeEffects", "mso",
    "QuickStylesGallery", "mso",
    "LineStyle", "mso",
    "LineWeight", "mso",
    "LineDashes", "mso",
    "LineArrowheads", "mso",

    ; --- 图片工具 (Picture Tools) ---
    "PictureChange", "mso",
    "PictureReset", "mso",
    "Crop", "mso",
    "CropToShape", "mso",
    "AspectRatio", "mso",
    "CompressPictures", "mso",
    "PictureColor", "mso",
    "PictureArtisticEffects", "mso",
    "PictureCorrections", "mso",
    "PictureBorder", "mso",
    "RemoveBackground", "mso",
    "OnlinePicture", "mso",
    "InsertScreenshot", "mso",
    
    "PictureCropAspectRatio1To1", "mso",
    "PictureCropAspectRatio2To3", "mso",
    "PictureCropAspectRatio3To4", "mso",
    "PictureCropAspectRatio3To5", "mso",
    "PictureCropAspectRatio4To5", "mso",
    "PictureCropAspectRatio3To2", "mso",
    "PictureCropAspectRatio4To3", "mso",
    "PictureCropAspectRatio5To3", "mso",
    "PictureCropAspectRatio5To4", "mso",
    "PictureCropAspectRatio16To9", "mso",
    "PictureCropAspectRatio16To10", "mso",
    "PictureFillCrop", "mso",
    "PictureFitCrop", "mso",

    ; --- 排列与位置 (Arrange & Position) ---
    "NudgeUp", "mso",
    "NudgeDown", "mso",
    "NudgeLeft", "mso",
    "NudgeRight", "mso",
    "SizeUp", "mso",
    "SizeDown", "mso",
    "SizeLeft", "mso",
    "SizeRight", "mso",
    "SizeObjectDialog", "mso",
    "SnapToGrid", "mso",
    "SnapToShapes", "mso",
    "Gridlines", "mso",
    "Guides", "mso",
    "ViewZoom", "mso",
    "FitToWindow", "mso",
    "ZoomToSelection", "mso",

    ; --- 表格工具 (Table Tools) ---
    "InsertRowsAbove", "mso",
    "InsertRowsBelow", "mso",
    "InsertColumnsLeft", "mso",
    "InsertColumnsRight", "mso",
    "DeleteRows", "mso",
    "DeleteColumns", "mso",
    "MergeCells", "mso",
    "SplitCells", "mso",
    "DistributeRows", "mso",
    "DistributeColumns", "mso",
    "TableBorders", "mso",
    "TableFillColor", "mso",

    ; --- 图表工具 (Chart Tools) ---
    "ChartType", "mso",
    "ChartData", "mso",
    "ChartLayout", "mso",
    "ChartStyles", "mso",
    "ChartAxes", "mso",
    "ChartGridlines", "mso",
    "ChartLegend", "mso",
    "ChartDataLabels", "mso",
    "ChartTrendline", "mso",

    ; --- 智能艺术图形 (SmartArt) ---
    "SmartArtAddShapeAfter", "mso",
    "SmartArtAddShapeBefore", "mso",
    "SmartArtAddShapeAbove", "mso",
    "SmartArtAddShapeBelow", "mso",
    "SmartArtChangeHierarchy", "mso",
    "SmartArtRTL", "mso",
    "SmartArtLarger", "mso",
    "SmartArtSmaller", "mso",
    "SmartArtReset", "mso",

    ; --- 其他常用 ---
    "HyperlinkInsert", "mso",
    "Duplicate", "mso",
    "Delete", "mso",
    "Copy", "mso",
    "Paste", "mso",
    "PasteSourceFormatting", "mso",
    "PasteMergeFormatting", "mso",
    "PastePicture", "mso",
    "Save", "mso",
    "Undo", "mso",
    "Redo", "mso",
    "SelectAll", "mso",
    "Find", "mso",
    "Replace", "mso",

    "AutoSaveSwitch",               "mso",
    "FileNewDefault",               "mso",
    "FileOpenUsingBackstage",       "mso",
    "FileSave",                     "mso",
    "FileSendAsAttachment",         "mso",
    "FilePrintQuick",               "mso",
    "PrintPreviewAndPrint",         "mso",
    "Spelling",                     "mso",
    "RedoOrRepeat",                 "mso",
    "SlideShowFromBeginning",       "mso",
    "Paste",                        "mso",
    "PasteSpecialDialog",           "mso",
    "Cut",                          "mso",
    "Copy",                         "mso",
    "PasteDuplicate",               "mso",
    "FormatPainter",                "mso",
    "ShowClipboard",                "mso",
    "DuplicateSelectedSlides",      "mso",
    "SlidesFromOutline",            "mso",
    "SlidesReuseSlides",            "mso",
    "SlideReset",                   "mso",
    "SectionAdd",                   "mso",
    "SectionRename",                "mso",
    "SectionMergeWithPrevious",     "mso",
    "SectionRemoveAll",             "mso",
    "SectionCollapseAll",           "mso",
    "SectionExpandAll",             "mso",
    "FontSizeIncrease",             "mso",
    "FontSizeDecrease",             "mso",
    "ClearFormatting",              "mso",
    "Bold",                         "mso",
    "Italic",                       "mso",
    "Underline",                    "mso",
    "Shadow",                       "mso",
    "Strikethrough",                "mso",
    "FontColorMoreColorsDialogPowerPoint", "mso",
    "EyedropperFillText",           "mso",
    "FontDialogPowerPoint",         "mso",
    "BulletsAndNumberingBulletsDialog", "mso",
    "BulletsAndNumberingNumberingDialog", "mso",
    "IndentDecrease",               "mso",
    "IndentIncrease",               "mso",
    "AlignLeft",                    "mso",
    "AlignCenter",                  "mso",
    "AlignRight",                   "mso",
    "AlignJustify",                 "mso",
    "AlignJustifyWithMixedLanguages", "mso",
    "AlignJustifyLow",              "mso",
    "ParagraphDistributed",         "mso",
    "AlignJustifyThai",             "mso",
    "TextDirectionLeftToRight",     "mso",
    "TextDirectionRightToLeft",     "mso",
    "ParagraphMoreColumnsDialog",   "mso",
    "TextDirectionMoreOptionsDialog", "mso",
    "TextAlignMoreOptionsDialog",   "mso",
    "ConvertToSmartArtMoreSmartArtGraphicsDialog", "mso",
    "PowerPointParagraphDialog",    "mso",
    "ObjectBringToFront",           "mso",
    "ObjectSendToBack",             "mso",
    "ObjectBringForward",           "mso",
    "ObjectSendBackward",           "mso",
    "ObjectsGroup",                 "mso",
    "ObjectsUngroup",               "mso",
    "ObjectsRegroup",               "mso",
    "ObjectsAlignLeftSmart",        "mso",
    "ObjectsAlignCenterHorizontalSmart", "mso",
    "ObjectsAlignRightSmart",       "mso",
    "ObjectsAlignTopSmart",         "mso",
    "ObjectsAlignMiddleVerticalSmart", "mso",
    "ObjectsAlignBottomSmart",      "mso",
    "AlignDistributeHorizontally",  "mso",
    "AlignDistributeVertically",    "mso",
    "ObjectsAlignRelativeToContainerSmart", "mso",
    "ObjectsAlignSelectedSmart",    "mso",
    "ObjectRotationOptionsDialog",  "mso",
    "SelectionPane",                "mso",
    "ObjectFillMoreColorsDialog",   "mso",
    "EyedropperFill",               "mso",
    "ObjectPictureFill",            "mso",
    "ShapeFillMoreGradientsDialog", "mso",
    "MoreTextureOptions",           "mso",
    "ObjectBorderOutlineColorMoreColorsDialog", "mso",
    "EyedropperOutline",            "mso",
    "LineStylesDialog",             "mso",
    "ArrowsMore",                   "mso",
    "_3DBevelOptionsDialog",        "mso",
    "ShadowOptionsDialog",          "mso",
    "ReflectionsMoreOptions",       "mso",
    "GlowColorMoreColorsDialog",    "mso",
    "EyedropperGlow",               "mso",
    "GlowsMoreOptions",             "mso",
    "SoftEdgesMoreOptions",         "mso",
    "_3DRotationOptionsDialog",     "mso",
    "ObjectFormatDialog",           "mso",
    "FindDialog",                   "mso",
    "ReplaceDialog",                "mso",
    "FontsReplaceFonts",            "mso",
    "SelectAll",                    "mso",
    "Dictate",                      "mso",
    "TableInsert",                  "mso",
    "TableDrawTable",               "mso",
    "ExcelSpreadsheetInsert",       "mso",
    "PictureInsertFromFilePowerPoint", "mso",
    "ClipArtInsertDialog",          "mso",
    "ScreenClipping",               "mso",
    "PhotoAlbumInsert",             "mso",
    "PhotoAlbumEdit",               "mso",
    "IconInsertFromFile",           "mso",
    "Insert3DModelFallback",        "mso",
    "Insert3DModelDefault",         "mso",
    "Insert3DModelFromFile",        "mso",
    "Insert3DModelFromOnline",      "mso",
    "SmartArtInsert",               "mso",
    "ChartInsert",                  "mso",
    "OfficeExtensionsAppStore",     "mso",
    "OfficeExtensionsDialog",       "mso",
    "OfficeExtensionsManageOtherAddins", "mso",
    "MSPPTInsertTableofContents",   "mso",
    "SectionZoomInsert",            "mso",
    "SlideZoomInsert",              "mso",
    "HyperlinkInsert",              "mso",
    "ActionInsert",                 "mso",
    "InsertNewComment",             "mso",
    "TextBoxInsert",                "mso",
    "TextBoxInsertHorizontal",      "mso",
    "TextBoxInsertVertical",        "mso",
    "HeaderFooterInsert",           "mso",
    "DateAndTimeInsert",            "mso",
    "NumberInsert",                 "mso",
    "OleObjectctInsert",            "mso",
    "EquationInsertNew",            "mso",
    "InkEquation",                  "mso",
    "SymbolInsert",                 "mso",
    "MovieFromClipOrganizerInsert", "mso",
    "MovieFromFileInsert",          "mso",
    "SoundInsertFromFile",          "mso",
    "SoundRecord",                  "mso",
    "ObjectScreenRecording",        "mso",
    "InsertMSForms",                "mso",
    "FingerPaintingMode",           "mso",
    "InkEraser",                    "mso",
    "PointEraser",                  "mso",
    "SegmentEraser",                "mso",
    "ShowRulerStencil",             "mso",
    "InkToTextAnalysis",            "mso",
    "InkToShapeAnalysis",           "mso",
    "InkToMathAnalysis",            "mso",
    "MathInputEditor",              "mso",
    "Replay",                       "mso",
    "ThemeSearchOfficeOnlinePowerPoint", "mso",
    "ThemeBrowseForThemesPowerPoint", "mso",
    "ThemeSaveCurrentPowerPoint",   "mso",
    "ThemeColorsCreateNew",         "mso",
    "ThemeColorsReset",             "mso",
    "ThemeFontsCreateNew",          "mso",
    "SlideBackgroundFormatDialog",  "mso",
    "SlideBackgroundReset",         "mso",
    "CustomSlideSize",              "mso",
    "LaunchFormatBackground",       "mso",
    "DesignerPane",                 "mso",
    "TransitionPreview",            "mso",
    "TransitionSoundLoopUntilNextSound", "mso",
    "TransitionDuration",           "mso",
    "SlideTransitionApplyToAll",    "mso",
    "SlideTransitionOnMouseClick",  "mso",
    "SlideTransitionAutomaticallyAfter", "mso",
    "AnimationPreview",             "mso",
    "AnimationAutoPreview",         "mso",
    "AnimationCustomEntranceDialog", "mso",
    "AnimationCustomEmphasisDialog", "mso",
    "AnimationCustomExitDialog",    "mso",
    "AnimationCustomPathDialog",    "mso",
    "AnimationCustomActionVerbDialog", "mso",
    "EffectOptionsDialog",          "mso",
    "AnimationCustomAddEntranceDialog", "mso",
    "AnimationCustomAddEmphasisDialog", "mso",
    "AnimationCustomAddExitDialog", "mso",
    "AnimationCustomAddPathDialog", "mso",
    "AnimationCustomAddActionVerbDlog", "mso",
    "AnimationCustom",              "mso",
    "AnimationPainter",             "mso",
    "AnimationDuration",            "mso",
    "AnimationDelay",               "mso",
    "AnimationMoveEarlier",         "mso",
    "AnimationMoveLater",           "mso",
    "SlideShowFromCurrent",         "mso",
    "BroadcastSlideShow",           "mso",
    "BroadcastSlideShowLync",       "mso",
    "BroadcastSlideShowGeneric",    "mso",
    "SlideShowSetUpDialog",         "mso",
    "SlideHide",                    "mso",
    "SlideShowRehearseTimings",     "mso",
    "RecordNarrationFromCurrentSlide", "mso",
    "RecordNarration",              "mso",
    "SlideShowPlayNarrations",      "mso",
    "SlideShowUseRehearsedTimings", "mso",
    "MediaControlsShow",            "mso",
    "SlideShowUsePresenterView",    "mso",
    "ViewThumbnailViewPowerPoint",  "mso",
    "ViewOutlineViewPowerPoint",    "mso",
    "ViewSlideSorterView",          "mso",
    "ViewNotesPageView",            "mso",
    "ViewSlideShowReadingView",     "mso",
    "ViewSlideMasterView",          "mso",
    "ViewHandoutMasterView",        "mso",
    "ViewNotesMasterView",          "mso",
    "ViewRulerPowerPoint",          "mso",
    "ViewGridlinesPowerPoint",      "mso",
    "GuidesShowHide",               "mso",
    "ShowNotes",                    "mso",
    "GridSettings",                 "mso",
    "ViewDirectionLeftToRight",     "mso",
    "ViewDirectionRightToLeft",     "mso",
    "ZoomDialog",                   "mso",
    "ZoomFitToWindow",              "mso",
    "ViewDisplayInHighContrast",    "mso",
    "ViewDisplayInColor",           "mso",
    "ViewDisplayInGrayscale",       "mso",
    "ViewDisplayInPureBlackAndWhite", "mso",
    "WindowNew",                    "mso",
    "WindowsArrangeAll",            "mso",
    "WindowsCascade",               "mso",
    "WindowMoveSplit",              "mso",
    "WindowMoreWindowsDialog",      "mso",
    "MacroPlay",                    "mso",
    "VisualBasic",                  "mso",
    "MacroSecurity",                "mso",
    "AddInManager",                 "mso",
    "ComAddInsDialog",              "mso",
    "ActiveXLabel",                 "mso",
    "ActiveXTextBox",               "mso",
    "ActiveXSpinButton",            "mso",
    "ActiveXButton",                "mso",
    "ActiveXImage",                 "mso",
    "ActiveXScrollBar",             "mso",
    "ActiveXCheckBox",              "mso",
    "ActiveXRadioButton",           "mso",
    "ActiveXComboBox",              "mso",
    "ActiveXListBox",               "mso",
    "ActiveXToggleButton",          "mso",
    "MoreControlsDialog",           "mso",
    "ControlProperties",            "mso",
    "ViewVisualBasicCode",          "mso",
    "SlideNew",                     "mso",
    "SlideMasterInsertLayout",      "mso",
    "SlideDelete",                  "mso",
    "SlideMasterRenameMaster",      "mso",
    "SlideMasterPreserveMaster",    "mso",
    "SlideMasterMasterLayout",      "mso",
    "SlideMasterContentPlaceholder", "mso",
    "SlideMasterVerticalContentPla", "mso",
    "SlideMasterTextPlaceholderIns", "mso",
    "SlideMasterVerticalTextPlaceh", "mso",
    "SlideMasterPicturePlaceholder", "mso",
    "SlideMasterChartPlaceholderIn", "mso",
    "SlideMasterTablePlaceholderIn", "mso",
    "SlideMasterDiagramPlaceholder", "mso",
    "SlideMasterMediaPlaceholderIn", "mso",
    "SlideMasterClipArtPlaceholder", "mso",
    "SlideMasterShowTitle",         "mso",
    "SlideMasterShowFooters",       "mso",
    "SlideBackgroundHideGraphics",  "mso",
    "MasterViewClose",              "mso",
    "PasteAsHyperlink",             "mso",
    "PasteBitmap",                  "mso",
    "PasteGif",                     "mso",
    "PastePng",                     "mso",
    "PasteJpeg",                    "mso",
    "PasteTextOnly",                "mso",
    "PasteAsPicture",               "mso",
    "PasteSourceFormatting",        "mso",
    "PasteDestinationTheme",        "mso",
    "ExportToVideo",                "mso",
    "ShapeRectangle",               "mso",
    "ShapeOval",                    "mso",
    "ShapeElbowConnectorArrow",     "mso",
    "ObjectRotateLeft90",           "mso",
    "ShapeStraightConnectorArrow",  "mso",
    "ShapeElbowConnector",          "mso",
    "ObjectSetShapeDefaults",       "mso",
    "ShapeRoundedRectangle",        "mso",
    "ShapeStraightConnector",       "mso",
    "ObjectFlipHorizontal",         "mso",
    "ShapeRightArrow",              "mso",
    "ObjectRotateFree",             "mso",
    "ShapeDownArrow",               "mso",
    "ObjectFlipVertical",           "mso",
    "ObjectRotateRight90",          "mso",
    "ShapeRoundedRectangularCallout", "mso",
    "ShapeIsoscelesTriangle",       "mso",
    "ShapesMoreShapes",             "mso",
    "ShapeLeftBrace",               "mso",
    "ObjectNudgeDown",              "mso",
    "ShapeRightBrace",              "mso",
    "PickUpStyle",                  "mso",
    "About",                        "mso",

    ; --- sendinput ----------------------------------------------------------------

    "+{MButton}", "send",
    "+{LButton}", "send",
    "!+{Tab}", "send",
    "+#{Left}", "send",
    "^a", "send",
    "^+a", "send",
    "#a", "send",
    "!a", "send",
    "^b", "send",
    "^+b", "send",
    "#b", "send",
    "!b", "send",
    "^c", "send",
    "^+c", "send",
    "#c", "send",
    "!c", "send",
    "^d", "send",
    "^+d", "send",
    "#d", "send",
    "!d", "send",
    "^e", "send",
    "^+e", "send",
    "#e", "send",
    "!e", "send",
    "^f", "send",
    "^+f", "send",
    "#f", "send",
    "!f", "send",
    "^g", "send",
    "^+g", "send",
    "#g", "send",
    "!g", "send",
    "^h", "send",
    "^+h", "send",
    "#h", "send",
    "!h", "send",
    "^i", "send",
    "^+i", "send",
    "#i", "send",
    "!i", "send",
    "^j", "send",
    "^+j", "send",
    "#j", "send",
    "!j", "send",
    "^k", "send",
    "^+k", "send",
    "#k", "send",
    "!k", "send",
    "^l", "send",
    "^+l", "send",
    "#l", "send",
    "!l", "send",
    "^m", "send",
    "^+m", "send",
    "#m", "send",
    "!m", "send",
    "^n", "send",
    "^+n", "send",
    "#n", "send",
    "!n", "send",
    "^o", "send",
    "^+o", "send",
    "#o", "send",
    "!o", "send",
    "^p", "send",
    "^+p", "send",
    "#p", "send",
    "!p", "send",
    "^q", "send",
    "^+q", "send",
    "#q", "send",
    "!q", "send",
    "^r", "send",
    "^+r", "send",
    "#r", "send",
    "!r", "send",
    "^s", "send",
    "^+s", "send",
    "#s", "send",
    "!s", "send",
    "^t", "send",
    "^+t", "send",
    "#t", "send",
    "!t", "send",
    "^u", "send",
    "^+u", "send",
    "#u", "send",
    "!u", "send",
    "^v", "send",
    "^+v", "send",
    "#v", "send",
    "!v", "send",
    "^w", "send",
    "^+w", "send",
    "#w", "send",
    "!w", "send",
    "^x", "send",
    "^+x", "send",
    "#x", "send",
    "!x", "send",
    "^y", "send",
    "^+y", "send",
    "#y", "send",
    "!y", "send",
    "^z", "send",
    "^+z", "send",
    "#z", "send",
    "!z", "send",
    "^;", "send",
    "^+;", "send",
    "#;", "send",
    "!;", "send",
    "{F1}", "send",
    "{F2}", "send",
    "{F3}", "send",
    "{F4}", "send",
    "{F5}", "send",
    "{F6}", "send",
    "{F7}", "send",
    "{F8}", "send",
    "{F9}", "send",
    "{F10}", "send",
    "{F11}", "send",
    "^{F1}", "send",
    "^{F2}", "send",
    "^{F3}", "send",
    "^{F4}", "send",
    "^{F5}", "send",
    "^{F6}", "send",
    "^{F7}", "send",
    "^{F8}", "send",
    "^{F9}", "send",
    "^{F10}", "send",
    "^{F11}", "send",
    "+{F1}", "send",
    "+{F2}", "send",
    "+{F3}", "send",
    "+{F4}", "send",
    "+{F5}", "send",
    "+{F6}", "send",
    "+{F7}", "send",
    "+{F8}", "send",
    "+{F9}", "send",
    "+{F10}", "send",
    "+{F11}", "send",
    "!{F1}", "send",
    "!{F2}", "send",
    "!{F3}", "send",
    "!{F4}", "send",
    "!{F5}", "send",
    "!{F6}", "send",
    "!{F7}", "send",
    "!{F8}", "send",
    "!{F9}", "send",
    "!{F10}", "send",
    "!{F11}", "send"
)

selection_type_map := Map(
    0, "none",
    1, "slides",
    2, "shapes",
    3, "text"
)

SHAPE_TYPE_MAP := Map(
    ; 数值, 常量名称,                              ; 说明
    30, "mso3DModel",                            ; 3D 模型
    1, "msoAutoShape",                           ; 自选图形
    2, "msoCallout",                             ; 标注
    20, "msoCanvas",                             ; 画布
    3, "msoChart",                               ; 图表
    4, "msoComment",                             ; 评论
    27, "msoContentApp",                         ; 内容 Office 加载项
    21, "msoDiagram",                            ; 图示
    7, "msoEmbeddedOLEObject",                   ; 嵌入式 OLE 对象
    8, "msoFormControl",                         ; 窗体控件
    5, "msoFreeform",                            ; 任意多边形
    28, "msoGraphic",                            ; 图形
    6, "msoGroup",                               ; 组
    24, "msoIgxGraphic",                         ; SmartArt 图形
    22, "msoInk",                                ; 墨迹
    23, "msoInkComment",                         ; 墨迹批注
    9, "msoLine",                                ; 折线图
    31, "msoLinked3DModel",                      ; 链接的 3D 模型
    29, "msoLinkedGraphic",                      ; 链接的图形
    10, "msoLinkedOLEObject",                    ; 链接 OLE 对象
    11, "msoLinkedPicture",                      ; 链接图片
    16, "msoMedia",                              ; 媒体
    12, "msoOLEControlObject",                   ; OLE 控件对象
    13, "msoPicture",                            ; 图片
    14, "msoPlaceholder",                        ; 占位符
    18, "msoScriptAnchor",                       ; 脚本定位标记
    -2, "msoShapeTypeMixed",                     ; 混合形状类型
    25, "msoSlicer",                             ; 切片器
    19, "msoTable",                              ; 表格
    17, "msoTextBox",                            ; 文本框
    15, "msoTextEffect",                         ; 文本效果
    26, "msoWebVideo"                            ; Web 视频
)

TEXT_4 := [
    "智领未来", "数实融合", "新质生产力", "绿色低碳",
    "自主创新", "全球布局", "提质增效", "降本增效",
    "敏捷迭代", "深度赋能", "生态共赢", "价值重塑",
    "精准洞察", "全域营销", "沉浸体验", "无缝协同",
    "智慧决策", "韧性增长", "安全可控", "开源节流",
    "跨界融合", "场景创新", "数据驱动", "云端协同",
    "人机协作", "虚实共生", "零碳转型", "循环经济",
    "高端智造", "专精特新", "品牌焕新", "用户至上",
    "长期主义", "稳健经营", "风险对冲", "合规先行",
    "人才强企", "文化铸魂", "组织激活", "效能飞跃",
    "技术突破", "产业升级", "市场深耕", "渠道下沉",
    "内容种草", "私域运营", "直播赋能", "社交裂变",
    "AI 赋能", "算力爆发", "算法优化", "模型迭代",
    "量子前沿", "生物制造", "空天经济", "深海探测",
    "能源革命", "储能创新", "氢能应用", "光伏增效",
    "智能网联", "车路协同", "低空经济", "无人配送",
    "元宇宙境", "数字孪生", "区块链网", "隐私计算",
    "柔性生产", "定制服务", "即时响应", "极致体验",
    "开放合作", "共享经济", "平台生态", "链式反应",
    "破局重生", "弯道超车", "换道领跑", "降维打击",
    "精细运营", "精益管理", "标准引领", "质量强国",
    "乡村振兴", "共同富裕", "民生福祉", "社会和谐",
    "文化自信", "国潮崛起", "东方美学", "匠心传承",
    "健康中国", "智慧医疗", "康养结合", "生命科学",
    "教育公平", "终身学习", "技能提升", "产教融合",
    "法治社会", "诚信体系", "公平正义", "平安建设",
    "美丽中国", "生态文明", "人与自然", "和谐共生"
]

TEXT_8 := [
    "数字转型实施方案", "项目管理优化策略", "战略规划部署方案", "宏观趋势分析报告",
    "竞争格局应对策略", "产业升级指导纲要", "区域发展布局规划", "长期愿景实施路径",
    "短期目标行动指南", "资源配置优化方案", "运营效能提升方案", "供应链路协同优化",
    "库存管理精简策略", "物流配送提速计划", "生产流程再造工程", "精益管理推行方案",
    "风险防控体系建设", "合规审计整改报告", "市场分析研究报告", "品牌建设推广方案",
    "营销渠道拓展计划", "客户画像分析洞察", "竞品对标分析报告", "公关危机处理预案",
    "产品创新设计方案", "技术架构升级方案", "数据安全防护措施", "用户体验改进计划",
    "团队建设发展规划", "人才培养实施方案", "成本控制优化策略", "效率提升行动计划",
    "质量管控体系构建", "业务流程改进方案", "客户服务提升计划", "技术架构升级方案",
    "人才培养实施方案", "质量管控体系构建", "成本控制优化策略", "效率提升行动计划",
    "品牌建设推广方案", "数据安全防护措施", "用户体验改进计划", "战略规划部署方案",
    "宏观趋势分析报告", "竞争格局应对策略", "产业升级指导纲要", "区域发展布局规划",
    "长期愿景实施路径", "短期目标行动指南", "资源配置优化方案", "顶层设计构建方案",
    "年度经营计划大纲", "运营效能提升方案", "供应链条协同优化", "库存管理精简策略",
    "物流配送提速计划", "生产流程再造工程", "精益管理推行方案", "风险防控体系建设"
]

TEXT_20 := [
    "深化数字化转型战略，全面推动企业高质量发展进程",
    "优化供应链管理流程，显著提升整体运营效率与效益",
    "加强核心技术自主研发，构建可持续创新竞争壁垒",
    "拓展全球市场业务布局，实现多元化国际发展战略",
    "完善人才培养激励机制，打造高素质专业化精英团队",
    "推进绿色低碳生产模式，践行社会责任与可持续发展",
    "强化风险防控体系建设，确保企业经营安全稳健运行",
    "提升客户服务体验标准，树立行业领先品牌形象口碑",
    "加速智能工厂建设步伐，引领制造业转型升级新方向",
    "整合线上线下营销渠道，最大化提升市场份额占有率",
    "落实精细化管理措施，有效控制成本并提高利润率",
    "探索新兴商业模式应用，激发组织内部活力与创新力",
    "构建开放共赢生态平台，携手合作伙伴共创美好未来",
    "加大研发投入力度，突破关键领域技术瓶颈与制约",
    "优化资产配置结构，实现资本运作效率最大化目标",
    "建立数据驱动决策机制，精准洞察市场趋势与变化",
    "弘扬企业文化核心价值观，凝聚全员奋斗共识与力量",
    "实施品牌国际化战略，提升中国智造全球影响力",
    "完善售后服务网络体系，快速响应客户需求与反馈",
    "推动产业协同创新发展，构建现代化经济体系新格局"
]

TEXT_30 := [
    "深化数字化转型战略全面布局，以创新驱动引领企业高质量可持续发展新征程",
    "优化全链路供应链管理流程，显著提升整体运营效率并最大化经济效益产出",
    "加强核心技术自主研发创新力度，构建具有全球竞争力的可持续技术壁垒",
    "拓展全球化市场业务战略布局，实现多元化国际发展战略与市场份额双增长",
    "完善全方位人才培养激励机制，打造高素质专业化精英团队以赋能组织发展",
    "深入推进绿色低碳生产模式转型，积极践行社会责任并实现可持续生态发展",
    "强化多层次风险防控体系建设，确保企业在复杂环境中经营安全稳健运行",
    "全面提升客户服务体验标准体系，树立行业领先品牌形象与卓越口碑影响力",
    "加速智能化数字工厂建设步伐，引领传统制造业转型升级与高质量发展方向",
    "深度整合线上线下全渠道营销，最大化提升市场份额占有率与品牌渗透能力",
    "全面落实精细化运营管理措施，有效控制成本支出并显著提高净利润率水平",
    "积极探索新兴商业模式创新应用，充分激发组织内部活力与持续创新驱动力",
    "构建开放共赢的产业生态平台，携手合作伙伴共创美好未来与商业价值新高",
    "加大前沿技术研发投入支持力度，突破关键领域技术瓶颈制约并掌握主动权",
    "优化多元化资产配置结构组合，实现资本运作效率最大化与企业价值目标",
    "建立数据驱动型科学决策机制，精准洞察市场趋势变化并快速响应客户需求",
    "弘扬企业文化核心价值观理念，凝聚全员奋斗共识与力量以推动战略目标达成",
    "全面实施品牌国际化发展战略，显著提升中国智造在全球市场的影响力地位",
    "完善覆盖全国售后服务网络体系，快速响应客户需求反馈并提升满意度指标",
    "推动产业链协同创新发展模式，构建现代化经济体系新格局并增强抗风险能力"
]

global super_power := True
global fn_mode := False
global prior_key := ""
global just_minimized_window := ""

; #endregion
